
document.addEventListener('DOMContentLoaded', () => {
  const titleInput = document.getElementById('title');
  const descriptionInput = document.getElementById('description');
  const authorInput = document.getElementById('author');
  const llmPrompt = document.getElementById('llm-prompt');
  const copyPromptButton = document.getElementById('copy-prompt-button');

  // Load saved data from localStorage
  titleInput.value = localStorage.getItem('title') || '';
  descriptionInput.value = localStorage.getItem('description') || '';
  authorInput.value = localStorage.getItem('author') || '';

  // Function to update the LLM prompt
  const updateLlmPrompt = () => {
    const title = titleInput.value;
    const description = descriptionInput.value;
    const author = authorInput.value;

    const gameGeneratorJS = `
// Class responsibilities:
// MyGameGenerator specifies the values (e.g. words, numbers) that show up in the game grid

// Notes:
// - Games start on level 0 (which is displayed as level 1 in the UI)

class MyGameGenerator {
  constructor() {

  }

  gameName() {
    return "Yes Wolfer"
  }

  generateMatchingValuesForLevel(level) {
    return ["yes"]
  }

  generateNonMatchingValuesForLevel(level) {
    return ["reallylongword"]
  }

  titleForLevel(level) {
    return "Eat the yes"
  }

  failureStringForValue(level, value) {
    return \`"\${value}" is wrong\`
  }

  // HunterBot pursues the user until the level is over or they
  // eliminate HunterBot via a Safe Space. Too challenging for young
  // kids.
  // Consider suppressing HunterBot entirely or on early levels
  // depending on target age for your game.
  isHunterBotAvailableOnLevel(level) {
    // HunterBot won't show up on the first level
    return level > 0;
  }
}
`;

    const prompt = `
Here is an example GameGenerator implementation for use by a Munchers-inspired game called Wolfer. The game generator produces "matching" values and "non-matching" values for every level. In a math-based game, a level's condition might be "< 4" and so matching values would include 0, 1, 2, 3. Non-matching values would include 4, 5, 6.

I want you to fill in an implementation of MyGameGenerator for a game that matches this description:

${description}

The code you generate must meet these requirements:

- At the top, have a comment that includes (be sure to fill in the values surrounded by <>):
Author: ${author}
Title: ${title}
Description: "${description}"
Date Created: <today's date>
Generated by: <a short name for yourself, the LLM that generated this string, including the name of the company that created you>

- All code MUST be contained within the MyGameGenerator class

- Matching and non-matching sets must be the same every time they are provided for a level. Do not use randomness.

- failureStringForValue should be concise yet informative. For example, if the level condition is "< 4", the failure string for value = 6 could be "6 is not < 4".


${gameGeneratorJS}
`;

    llmPrompt.value = prompt.trim();
  };

  // Update the LLM prompt on input
  titleInput.addEventListener('input', () => {
    localStorage.setItem('title', titleInput.value);
    updateLlmPrompt();
  });
  descriptionInput.addEventListener('input', () => {
    localStorage.setItem('description', descriptionInput.value);
    updateLlmPrompt();
  });
  authorInput.addEventListener('input', () => {
    localStorage.setItem('author', authorInput.value);
    updateLlmPrompt();
  });

  // Initial update
  updateLlmPrompt();

  // Initialize CodeMirror
  const gameCodeEditor = CodeMirror.fromTextArea(document.getElementById('game-code'), {
    mode: 'javascript',
    lineNumbers: true,
    theme: 'default' // You might want to add a CodeMirror theme CSS
  });

  // Load saved code from localStorage
  gameCodeEditor.setValue(localStorage.getItem('gameCode') || '');

  // Save code as the user types
  gameCodeEditor.on('change', () => {
    localStorage.setItem('gameCode', gameCodeEditor.getValue());
    invalidateDebugSession();
    const errorMessageElement = document.getElementById('error-message');
    if (errorMessageElement.textContent !== '') {
      errorMessageElement.style.color = 'gray';
    }
  });

  // Show a toast notification in the center of the screen
  const showToast = (message) => {
    const toast = document.createElement('div');
    toast.className = 'toast';
    toast.textContent = message;
    document.body.appendChild(toast);

    toast.classList.add('show');
    setTimeout(() => {
      document.body.removeChild(toast);
    }, 1000);
  };

  // Copy to clipboard
  copyPromptButton.addEventListener('click', () => {
    llmPrompt.select();
    document.execCommand('copy');
    showToast('Copied');
  });

  const copyGameCodeButton = document.getElementById('copy-game-code-button');
  copyGameCodeButton.addEventListener('click', () => {
    const codeToCopy = gameCodeEditor.getValue();
    navigator.clipboard.writeText(codeToCopy).then(() => {
      showToast('Copied');
    }).catch(err => {
      console.error('Failed to copy game code: ', err);
    });
  });

  window.loadCode = () => {
    console.log("Load Code button clicked");
    const errorMessageElement = document.getElementById('error-message');
    errorMessageElement.textContent = ''; // Clear previous error message
    errorMessageElement.style.color = 'red'; // Reset color to red for new errors

    // Warning: this pattern is not generally safe because the code being loaded
    // is user-entered (even worse: it's LLM generated by someone who is likely
    // not reviewing it).
    // This is ok on this specific web page because there is no user session,
    // sensitive cookies, access to a backend, etc.

    let userClass = null;

    const code = gameCodeEditor.getValue();

    try {
      const fn = new Function(code + '; return typeof MyGameGenerator !== "undefined" ? MyGameGenerator : null;');
      userClass = fn();

      if (!userClass) {
        throw new Error("MyGameGenerator class not found. Make sure the class is defined and named correctly.");
      }

      console.log("Loaded custom game generator successfully");
    } catch (e) {
      console.log('Error loading custom game generator: ' + e.message);
      errorMessageElement.textContent = e.message;
    }

    GameGenerators_classes[GameGenerators[gameName].className] = userClass;

    if (userClass) {
      gameController = createGameController();
    }
  };

  const invalidateDebugSession = () => {
    if (gameController) {
      console.log("Invalidating gameController");
      gameController.gameEngine.pauseGame();
      gameController.invalidate()
      gameController = null;
    } else {
      //console.log("No gameController exists to invalidate: " + gameController);
    }
  };

  window.resetForm = () => {
    const confirmation = confirm("Resetting this form will permanently delete title, description, author, and all code entered below. Would you like to reset this form?");
    if (confirmation) {
      titleInput.value = '';
      descriptionInput.value = '';
      authorInput.value = '';
      gameCodeEditor.setValue('');
      const errorMessageElement = document.getElementById('error-message');
      errorMessageElement.textContent = '';

      localStorage.removeItem('title');
      localStorage.removeItem('description');
      localStorage.removeItem('author');
      localStorage.removeItem('gameCode');

      updateLlmPrompt();
    }
  };
});
