// Author: Emerson
// Title: Dinosaurs
// Description: "Each level is a category that applies to dinosaurs (eg period like Triassic, diet like omnivore, family like cerstopsian, or other fun categories). Correct answers are dinosaurs that match the category (like T-Rex is a carnivore) and incorrect answers are dinosaurs that do not match the category (like Ankylosaurus is not a carnivore)."
// Date Created: Monday, November 24, 2025
// Generated by: Gemini (Google)

class GameGenerator_Dinosaurs extends MAGameGenerator {
  constructor() {
    super();

    // Database of dinosaurs with their attributes to ensure deterministic gameplay
    this.dinosaurs = [
      { name: "T-Rex", diet: "Carnivore", period: "Cretaceous", type: "Theropod" },
      { name: "Triceratops", diet: "Herbivore", period: "Cretaceous", type: "Ceratopsian" },
      { name: "Stegosaurus", diet: "Herbivore", period: "Jurassic", type: "Stegosaur" },
      { name: "Velociraptor", diet: "Carnivore", period: "Cretaceous", type: "Theropod" },
      { name: "Brachiosaurus", diet: "Herbivore", period: "Jurassic", type: "Sauropod" },
      { name: "Ankylosaurus", diet: "Herbivore", period: "Cretaceous", type: "Ankylosaur" },
      { name: "Spinosaurus", diet: "Carnivore", period: "Cretaceous", type: "Theropod" },
      { name: "Allosaurus", diet: "Carnivore", period: "Jurassic", type: "Theropod" },
      { name: "Diplodocus", diet: "Herbivore", period: "Jurassic", type: "Sauropod" },
      { name: "Parasaurolophus", diet: "Herbivore", period: "Cretaceous", type: "Hadrosaur" },
      { name: "Dilophosaurus", diet: "Carnivore", period: "Jurassic", type: "Theropod" },
      { name: "Iguanodon", diet: "Herbivore", period: "Cretaceous", type: "Ornithopod" }
    ];

    // Level definitions using modulo arithmetic in helper methods to support infinite play
    this.levelConfigs = [
      {
        id: "carnivore",
        title: "Eat Carnivores",
        categoryDescription: "a Carnivore", // Used for failure text
        matcher: (dino) => dino.diet === "Carnivore"
      },
      {
        id: "herbivore",
        title: "Eat Herbivores",
        categoryDescription: "a Herbivore",
        matcher: (dino) => dino.diet === "Herbivore"
      },
      {
        id: "jurassic",
        title: "Find Jurassic Dinos",
        categoryDescription: "from the Jurassic",
        matcher: (dino) => dino.period === "Jurassic"
      },
      {
        id: "cretaceous",
        title: "Find Cretaceous Dinos",
        categoryDescription: "from the Cretaceous",
        matcher: (dino) => dino.period === "Cretaceous"
      },
      {
        id: "theropod",
        title: "Eat Theropods",
        categoryDescription: "a Theropod",
        matcher: (dino) => dino.type === "Theropod"
      },
      {
        id: "sauropod",
        title: "Eat Sauropods",
        categoryDescription: "a Sauropod",
        matcher: (dino) => dino.type === "Sauropod"
      }
    ];
  }

  gameName() {
    return "Dino Wolfer";
  }

  // Helper to get the configuration for the current level (loops if levels exceed config length)
  _getConfigForLevel(level) {
    return this.levelConfigs[level % this.levelConfigs.length];
  }

  generateMatchingValuesForLevel(level) {
    const config = this._getConfigForLevel(level);
    // Filter dinosaurs that match the criteria and map to their names
    return this.dinosaurs
      .filter(dino => config.matcher(dino))
      .map(dino => dino.name);
  }

  generateNonMatchingValuesForLevel(level) {
    const config = this._getConfigForLevel(level);
    // Filter dinosaurs that DO NOT match the criteria and map to their names
    return this.dinosaurs
      .filter(dino => !config.matcher(dino))
      .map(dino => dino.name);
  }

  titleForLevel(level) {
    return this._getConfigForLevel(level).title;
  }

  failureStringForValue(level, value) {
    const config = this._getConfigForLevel(level);
    // Example output: "Stegosaurus is not a Carnivore" or "T-Rex is not from the Jurassic"
    return `${value} is not ${config.categoryDescription}`;
  }

  // HunterBot pursues the user until the level is over or they
  // eliminate HunterBot via a Safe Space. Too challenging for young
  // kids.
  isHunterBotAvailableOnLevel(level) {
    // HunterBot won't show up on the first level to allow learning mechanics
    return level > 0;
  }
}

// export as module and register if required
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { GameGenerator_Dinosaurs };
}

if (typeof GameGenerators_classes !== 'undefined') {
  GameGenerators_classes["GameGenerator_Dinosaurs"] = GameGenerator_Dinosaurs;
}
