class GameGenerator_SpanishVerbs extends MAGameGenerator {
  constructor() {
    super();
  }

  gameName() {
    return "Spanish Wolfer: Verbs";
  }

  static _wordDict() {
    const A = this.Attributes;
    return {
      "abre"            : (A.El),
      "abren"           : (A.Ellos),
      "abres"           : (A.Tu),
      "abrimos"         : (A.Nosotros),
      "abro"            : (A.Yo),
      "abrís"           : (A.Vosotros),
      "acepta"          : (A.El),
      "aceptamos"       : (A.Nosotros),
      "aceptan"         : (A.Ellos),
      "aceptas"         : (A.Tu),
      "acepto"          : (A.Yo),
      "aceptáis"        : (A.Vosotros),
      "anda"            : (A.El),
      "andamos"         : (A.Nosotros),
      "andan"           : (A.Ellos),
      "andas"           : (A.Tu),
      "ando"            : (A.Yo),
      "andáis"          : (A.Vosotros),
      "apaga"           : (A.El),
      "apagamos"        : (A.Nosotros),
      "apagan"          : (A.Ellos),
      "apagas"          : (A.Tu),
      "apago"           : (A.Yo),
      "apagáis"         : (A.Vosotros),
      "aprende"         : (A.El),
      "aprendemos"      : (A.Nosotros),
      "aprenden"        : (A.Ellos),
      "aprendes"        : (A.Tu),
      "aprendo"         : (A.Yo),
      "aprendéis"       : (A.Vosotros),
      "baila"           : (A.El),
      "bailamos"        : (A.Nosotros),
      "bailan"          : (A.Ellos),
      "bailas"          : (A.Tu),
      "bailo"           : (A.Yo),
      "bailáis"         : (A.Vosotros),
      "bebe"            : (A.El),
      "bebemos"         : (A.Nosotros),
      "beben"           : (A.Ellos),
      "bebes"           : (A.Tu),
      "bebo"            : (A.Yo),
      "bebéis"          : (A.Vosotros),
      "busca"           : (A.El),
      "buscamos"        : (A.Nosotros),
      "buscan"          : (A.Ellos),
      "buscas"          : (A.Tu),
      "busco"           : (A.Yo),
      "buscáis"         : (A.Vosotros),
      "cabe"            : (A.El),
      "cabemos"         : (A.Nosotros),
      "caben"           : (A.Ellos),
      "cabes"           : (A.Tu),
      "cabéis"          : (A.Vosotros),
      "cambia"          : (A.El),
      "cambiamos"       : (A.Nosotros),
      "cambian"         : (A.Ellos),
      "cambias"         : (A.Tu),
      "cambio"          : (A.Yo),
      "cambiáis"        : (A.Vosotros),
      "cancela"         : (A.El),
      "cancelamos"      : (A.Nosotros),
      "cancelan"        : (A.Ellos),
      "cancelas"        : (A.Tu),
      "cancelo"         : (A.Yo),
      "canceláis"       : (A.Vosotros),
      "canta"           : (A.El),
      "cantamos"        : (A.Nosotros),
      "cantan"          : (A.Ellos),
      "cantas"          : (A.Tu),
      "canto"           : (A.Yo),
      "cantáis"         : (A.Vosotros),
      "cerra"           : (A.El),
      "cerramos"        : (A.Nosotros),
      "cerran"          : (A.Ellos),
      "cerras"          : (A.Tu),
      "cerro"           : (A.Yo),
      "cerráis"         : (A.Vosotros),
      "come"            : (A.El),
      "comemos"         : (A.Nosotros),
      "comen"           : (A.Ellos),
      "comenzamos"      : (A.Nosotros),
      "comenzáis"       : (A.Vosotros),
      "comes"           : (A.Tu),
      "comienza"        : (A.El),
      "comienzan"       : (A.Ellos),
      "comienzas"       : (A.Tu),
      "comienzo"        : (A.Yo),
      "como"            : (A.Yo),
      "compra"          : (A.El),
      "compramos"       : (A.Nosotros),
      "compran"         : (A.Ellos),
      "compras"         : (A.Tu),
      "compro"          : (A.Yo),
      "compráis"        : (A.Vosotros),
      "coméis"          : (A.Vosotros),
      "conduce"         : (A.El),
      "conducen"        : (A.Ellos),
      "conduces"        : (A.Tu),
      "conducimos"      : (A.Nosotros),
      "conducís"        : (A.Vosotros),
      "conduzco"        : (A.Yo),
      "conoce"          : (A.El),
      "conocemos"       : (A.Nosotros),
      "conocen"         : (A.Ellos),
      "conoces"         : (A.Tu),
      "conocéis"        : (A.Vosotros),
      "conozco"         : (A.Yo),
      "contamos"        : (A.Nosotros),
      "contáis"         : (A.Vosotros),
      "corre"           : (A.El),
      "corremos"        : (A.Nosotros),
      "corren"          : (A.Ellos),
      "corres"          : (A.Tu),
      "corro"           : (A.Yo),
      "corréis"         : (A.Vosotros),
      "corta"           : (A.El),
      "cortamos"        : (A.Nosotros),
      "cortan"          : (A.Ellos),
      "cortas"          : (A.Tu),
      "corto"           : (A.Yo),
      "cortáis"         : (A.Vosotros),
      "cree"            : (A.El),
      "creemos"         : (A.Nosotros),
      "creen"           : (A.Ellos),
      "crees"           : (A.Tu),
      "creo"            : (A.Yo),
      "creéis"          : (A.Vosotros),
      "cuenta"          : (A.El),
      "cuentan"         : (A.Ellos),
      "cuentas"         : (A.Tu),
      "cuento"          : (A.Yo),
      "da"              : (A.El),
      "dais"            : (A.Vosotros),
      "damos"           : (A.Nosotros),
      "dan"             : (A.Ellos),
      "das"             : (A.Tu),
      "decimos"         : (A.Nosotros),
      "decís"           : (A.Vosotros),
      "deletrea"        : (A.El),
      "deletreamos"     : (A.Nosotros),
      "deletrean"       : (A.Ellos),
      "deletreas"       : (A.Tu),
      "deletreo"        : (A.Yo),
      "deletreáis"      : (A.Vosotros),
      "desea"           : (A.El),
      "deseamos"        : (A.Nosotros),
      "desean"          : (A.Ellos),
      "deseas"          : (A.Tu),
      "deseo"           : (A.Yo),
      "deseáis"         : (A.Vosotros),
      "despertamos"     : (A.Nosotros),
      "despertáis"      : (A.Vosotros),
      "despierta"       : (A.El),
      "despiertan"      : (A.Ellos),
      "despiertas"      : (A.Tu),
      "despierto"       : (A.Yo),
      "dibuja"          : (A.El),
      "dibujamos"       : (A.Nosotros),
      "dibujan"         : (A.Ellos),
      "dibujas"         : (A.Tu),
      "dibujo"          : (A.Yo),
      "dibujáis"        : (A.Vosotros),
      "dice"            : (A.El),
      "dicen"           : (A.Ellos),
      "dices"           : (A.Tu),
      "digo"            : (A.Yo),
      "dormimos"        : (A.Nosotros),
      "dormís"          : (A.Vosotros),
      "doy"             : (A.Yo),
      "duerme"          : (A.El),
      "duermen"         : (A.Ellos),
      "duermes"         : (A.Tu),
      "duermo"          : (A.Yo),
      "encendemos"      : (A.Nosotros),
      "encendéis"       : (A.Vosotros),
      "enciende"        : (A.El),
      "encienden"       : (A.Ellos),
      "enciendes"       : (A.Tu),
      "enciendo"        : (A.Yo),
      "encontramos"     : (A.Nosotros),
      "encontráis"      : (A.Vosotros),
      "encuentra"       : (A.El),
      "encuentran"      : (A.Ellos),
      "encuentras"      : (A.Tu),
      "encuentro"       : (A.Yo),
      "entendemos"      : (A.Nosotros),
      "entendéis"       : (A.Vosotros),
      "entiende"        : (A.El),
      "entienden"       : (A.Ellos),
      "entiendes"       : (A.Tu),
      "entiendo"        : (A.Yo),
      "enviamos"        : (A.Nosotros),
      "enviáis"         : (A.Vosotros),
      "envía"           : (A.El),
      "envían"          : (A.Ellos),
      "envías"          : (A.Tu),
      "envío"           : (A.Yo),
      "eres"            : (A.Tu),
      "es"              : (A.El),
      "escribe"         : (A.El),
      "escriben"        : (A.Ellos),
      "escribes"        : (A.Tu),
      "escribimos"      : (A.Nosotros),
      "escribo"         : (A.Yo),
      "escribís"        : (A.Vosotros),
      "escucha"         : (A.El),
      "escuchamos"      : (A.Nosotros),
      "escuchan"        : (A.Ellos),
      "escuchas"        : (A.Tu),
      "escucho"         : (A.Yo),
      "escucháis"       : (A.Vosotros),
      "espera"          : (A.El),
      "esperamos"       : (A.Nosotros),
      "esperan"         : (A.Ellos),
      "esperas"         : (A.Tu),
      "espero"          : (A.Yo),
      "esperáis"        : (A.Vosotros),
      "estamos"         : (A.Nosotros),
      "estoy"           : (A.Yo),
      "estudia"         : (A.El),
      "estudiamos"      : (A.Nosotros),
      "estudian"        : (A.Ellos),
      "estudias"        : (A.Tu),
      "estudio"         : (A.Yo),
      "estudiáis"       : (A.Vosotros),
      "está"            : (A.El),
      "estáis"          : (A.Vosotros),
      "están"           : (A.Ellos),
      "estás"           : (A.Tu),
      "explica"         : (A.El),
      "explicamos"      : (A.Nosotros),
      "explican"        : (A.Ellos),
      "explicas"        : (A.Tu),
      "explico"         : (A.Yo),
      "explicáis"       : (A.Vosotros),
      "firma"           : (A.El),
      "firmamos"        : (A.Nosotros),
      "firman"          : (A.Ellos),
      "firmas"          : (A.Tu),
      "firmo"           : (A.Yo),
      "firmáis"         : (A.Vosotros),
      "fuma"            : (A.El),
      "fumamos"         : (A.Nosotros),
      "fuman"           : (A.Ellos),
      "fumas"           : (A.Tu),
      "fumo"            : (A.Yo),
      "fumáis"          : (A.Vosotros),
      "gasta"           : (A.El),
      "gastamos"        : (A.Nosotros),
      "gastan"          : (A.Ellos),
      "gastas"          : (A.Tu),
      "gasto"           : (A.Yo),
      "gastáis"         : (A.Vosotros),
      "goza"            : (A.El),
      "gozamos"         : (A.Nosotros),
      "gozan"           : (A.Ellos),
      "gozas"           : (A.Tu),
      "gozo"            : (A.Yo),
      "gozáis"          : (A.Vosotros),
      "ha"              : (A.El),
      "habla"           : (A.El),
      "hablamos"        : (A.Nosotros),
      "hablan"          : (A.Ellos),
      "hablas"          : (A.Tu),
      "hablo"           : (A.Yo),
      "habláis"         : (A.Vosotros),
      "habéis"          : (A.Vosotros),
      "hace"            : (A.El),
      "hacemos"         : (A.Nosotros),
      "hacen"           : (A.Ellos),
      "haces"           : (A.Tu),
      "hacéis"          : (A.Vosotros),
      "hago"            : (A.Yo),
      "han"             : (A.Ellos),
      "has"             : (A.Tu),
      "he"              : (A.Yo),
      "hemos"           : (A.Nosotros),
      "intenta"         : (A.El),
      "intentamos"      : (A.Nosotros),
      "intentan"        : (A.Ellos),
      "intentas"        : (A.Tu),
      "intento"         : (A.Yo),
      "intentáis"       : (A.Vosotros),
      "juega"           : (A.El),
      "juegan"          : (A.Ellos),
      "juegas"          : (A.Tu),
      "juego"           : (A.Yo),
      "jugamos"         : (A.Nosotros),
      "jugáis"          : (A.Vosotros),
      "lee"             : (A.El),
      "leemos"          : (A.Nosotros),
      "leen"            : (A.Ellos),
      "lees"            : (A.Tu),
      "leo"             : (A.Yo),
      "leéis"           : (A.Vosotros),
      "limpia"          : (A.El),
      "limpiamos"       : (A.Nosotros),
      "limpian"         : (A.Ellos),
      "limpias"         : (A.Tu),
      "limpio"          : (A.Yo),
      "limpiáis"        : (A.Vosotros),
      "llena"           : (A.El),
      "llenamos"        : (A.Nosotros),
      "llenan"          : (A.Ellos),
      "llenas"          : (A.Tu),
      "lleno"           : (A.Yo),
      "llenáis"         : (A.Vosotros),
      "me caigo"        : (A.Yo),
      "me preocupo"     : (A.Yo),
      "me quejo"        : (A.Yo),
      "me siento"       : (A.Yo),
      "mira"            : (A.El),
      "miramos"         : (A.Nosotros),
      "miran"           : (A.Ellos),
      "miras"           : (A.Tu),
      "miro"            : (A.Yo),
      "miráis"          : (A.Vosotros),
      "nada"            : (A.El),
      "nadamos"         : (A.Nosotros),
      "nadan"           : (A.Ellos),
      "nadas"           : (A.Tu),
      "nado"            : (A.Yo),
      "nadáis"          : (A.Vosotros),
      "necesita"        : (A.El),
      "necesitamos"     : (A.Nosotros),
      "necesitan"       : (A.Ellos),
      "necesitas"       : (A.Tu),
      "necesito"        : (A.Yo),
      "necesitáis"      : (A.Vosotros),
      "nos caemos"      : (A.Nosotros),
      "nos preocupamos" : (A.Nosotros),
      "nos quejamos"    : (A.Nosotros),
      "nos sentamos"    : (A.Nosotros),
      "oigo"            : (A.Yo),
      "olvida"          : (A.El),
      "olvidamos"       : (A.Nosotros),
      "olvidan"         : (A.Ellos),
      "olvidas"         : (A.Tu),
      "olvido"          : (A.Yo),
      "olvidáis"        : (A.Vosotros),
      "organiza"        : (A.El),
      "organizamos"     : (A.Nosotros),
      "organizan"       : (A.Ellos),
      "organizas"       : (A.Tu),
      "organizo"        : (A.Yo),
      "organizáis"      : (A.Vosotros),
      "os caéis"        : (A.Vosotros),
      "os preocupáis"   : (A.Vosotros),
      "os quejáis"      : (A.Vosotros),
      "os sentáis"      : (A.Vosotros),
      "oye"             : (A.El),
      "oyen"            : (A.Ellos),
      "oyes"            : (A.Tu),
      "oímos"           : (A.Nosotros),
      "oís"             : (A.Vosotros),
      "paga"            : (A.El),
      "pagamos"         : (A.Nosotros),
      "pagan"           : (A.Ellos),
      "pagas"           : (A.Tu),
      "pago"            : (A.Yo),
      "pagáis"          : (A.Vosotros),
      "peina"           : (A.El),
      "peinamos"        : (A.Nosotros),
      "peinan"          : (A.Ellos),
      "peinas"          : (A.Tu),
      "peino"           : (A.Yo),
      "peináis"         : (A.Vosotros),
      "pensamos"        : (A.Nosotros),
      "pensáis"         : (A.Vosotros),
      "perdemos"        : (A.Nosotros),
      "perdéis"         : (A.Vosotros),
      "piensa"          : (A.El),
      "piensan"         : (A.Ellos),
      "piensas"         : (A.Tu),
      "pienso"          : (A.Yo),
      "pierde"          : (A.El),
      "pierden"         : (A.Ellos),
      "pierdes"         : (A.Tu),
      "pierdo"          : (A.Yo),
      "podemos"         : (A.Nosotros),
      "podéis"          : (A.Vosotros),
      "pone"            : (A.El),
      "ponemos"         : (A.Nosotros),
      "ponen"           : (A.Ellos),
      "pones"           : (A.Tu),
      "pongo"           : (A.Yo),
      "ponéis"          : (A.Vosotros),
      "pregunta"        : (A.El),
      "preguntamos"     : (A.Nosotros),
      "preguntan"       : (A.Ellos),
      "preguntas"       : (A.Tu),
      "pregunto"        : (A.Yo),
      "preguntáis"      : (A.Vosotros),
      "presta"          : (A.El),
      "prestamos"       : (A.Nosotros),
      "prestan"         : (A.Ellos),
      "prestas"         : (A.Tu),
      "presto"          : (A.Yo),
      "prestáis"        : (A.Vosotros),
      "puede"           : (A.El),
      "pueden"          : (A.Ellos),
      "puedes"          : (A.Tu),
      "puedo"           : (A.Yo),
      "quepo"           : (A.Yo),
      "queremos"        : (A.Nosotros),
      "queréis"         : (A.Vosotros),
      "quiere"          : (A.El),
      "quieren"         : (A.Ellos),
      "quieres"         : (A.Tu),
      "quiero"          : (A.Yo),
      "repara"          : (A.El),
      "reparamos"       : (A.Nosotros),
      "reparan"         : (A.Ellos),
      "reparas"         : (A.Tu),
      "reparo"          : (A.Yo),
      "reparáis"        : (A.Vosotros),
      "responde"        : (A.El),
      "respondemos"     : (A.Nosotros),
      "responden"       : (A.Ellos),
      "respondes"       : (A.Tu),
      "respondo"        : (A.Yo),
      "respondéis"      : (A.Vosotros),
      "rompe"           : (A.El),
      "rompemos"        : (A.Nosotros),
      "rompen"          : (A.Ellos),
      "rompes"          : (A.Tu),
      "rompo"           : (A.Yo),
      "rompéis"         : (A.Vosotros),
      "sabe"            : (A.El),
      "sabemos"         : (A.Nosotros),
      "saben"           : (A.Ellos),
      "sabes"           : (A.Tu),
      "sabéis"          : (A.Vosotros),
      "se cae"          : (A.El),
      "se caen"         : (A.Ellos),
      "se preocupa"     : (A.El),
      "se preocupan"    : (A.Ellos),
      "se queja"        : (A.El),
      "se quejan"       : (A.Ellos),
      "se sienta"       : (A.El),
      "se sientan"      : (A.Ellos),
      "sentimos"        : (A.Nosotros),
      "sentís"          : (A.Vosotros),
      "siente"          : (A.El),
      "sienten"         : (A.Ellos),
      "sientes"         : (A.Tu),
      "siento"          : (A.Yo),
      "sois"            : (A.Vosotros),
      "somos"           : (A.Nosotros),
      "son"             : (A.Ellos),
      "soy"             : (A.Yo),
      "sé"              : (A.Yo),
      "te caes"         : (A.Tu),
      "te preocupas"    : (A.Tu),
      "te quejas"       : (A.Tu),
      "te sientas"      : (A.Tu),
      "tenemos"         : (A.Nosotros),
      "tengo"           : (A.Yo),
      "tenéis"          : (A.Vosotros),
      "termina"         : (A.El),
      "terminamos"      : (A.Nosotros),
      "terminan"        : (A.Ellos),
      "terminas"        : (A.Tu),
      "termino"         : (A.Yo),
      "termináis"       : (A.Vosotros),
      "tiene"           : (A.El),
      "tienen"          : (A.Ellos),
      "tienes"          : (A.Tu),
      "toma"            : (A.El),
      "tomamos"         : (A.Nosotros),
      "toman"           : (A.Ellos),
      "tomas"           : (A.Tu),
      "tomo"            : (A.Yo),
      "tomáis"          : (A.Vosotros),
      "tose"            : (A.El),
      "tosemos"         : (A.Nosotros),
      "tosen"           : (A.Ellos),
      "toses"           : (A.Tu),
      "toso"            : (A.Yo),
      "toséis"          : (A.Vosotros),
      "trabaja"         : (A.El),
      "trabajamos"      : (A.Nosotros),
      "trabajan"        : (A.Ellos),
      "trabajas"        : (A.Tu),
      "trabajo"         : (A.Yo),
      "trabajáis"       : (A.Vosotros),
      "traduce"         : (A.El),
      "traducen"        : (A.Ellos),
      "traduces"        : (A.Tu),
      "traducimos"      : (A.Nosotros),
      "traducís"        : (A.Vosotros),
      "traduzco"        : (A.Yo),
      "trae"            : (A.El),
      "traemos"         : (A.Nosotros),
      "traen"           : (A.Ellos),
      "traes"           : (A.Tu),
      "traigo"          : (A.Yo),
      "traéis"          : (A.Vosotros),
      "usa"             : (A.El),
      "usamos"          : (A.Nosotros),
      "usan"            : (A.Ellos),
      "usas"            : (A.Tu),
      "uso"             : (A.Yo),
      "usáis"           : (A.Vosotros),
      "utiliza"         : (A.El),
      "utilizamos"      : (A.Nosotros),
      "utilizan"        : (A.Ellos),
      "utilizas"        : (A.Tu),
      "utilizo"         : (A.Yo),
      "utilizáis"       : (A.Vosotros),
      "va"              : (A.El),
      "vais"            : (A.Vosotros),
      "vamos"           : (A.Nosotros),
      "van"             : (A.Ellos),
      "vas"             : (A.Tu),
      "ve"              : (A.El),
      "vemos"           : (A.Nosotros),
      "ven"             : (A.Ellos),
      "vende"           : (A.El),
      "vendemos"        : (A.Nosotros),
      "venden"          : (A.Ellos),
      "vendes"          : (A.Tu),
      "vendo"           : (A.Yo),
      "vendéis"         : (A.Vosotros),
      "vengo"           : (A.Yo),
      "venimos"         : (A.Nosotros),
      "venís"           : (A.Vosotros),
      "veo"             : (A.Yo),
      "ves"             : (A.Tu),
      "vestimos"        : (A.Nosotros),
      "vestís"          : (A.Vosotros),
      "viaja"           : (A.El),
      "viajamos"        : (A.Nosotros),
      "viajan"          : (A.Ellos),
      "viajas"          : (A.Tu),
      "viajo"           : (A.Yo),
      "viajáis"         : (A.Vosotros),
      "viene"           : (A.El),
      "vienen"          : (A.Ellos),
      "vienes"          : (A.Tu),
      "viste"           : (A.El),
      "visten"          : (A.Ellos),
      "vistes"          : (A.Tu),
      "visto"           : (A.Yo),
      "vive"            : (A.El),
      "viven"           : (A.Ellos),
      "vives"           : (A.Tu),
      "vivimos"         : (A.Nosotros),
      "vivo"            : (A.Yo),
      "vivís"           : (A.Vosotros),
      "volamos"         : (A.Nosotros),
      "volvemos"        : (A.Nosotros),
      "volvéis"         : (A.Vosotros),
      "voláis"          : (A.Vosotros),
      "voy"             : (A.Yo),
      "vuela"           : (A.El),
      "vuelan"          : (A.Ellos),
      "vuelas"          : (A.Tu),
      "vuelo"           : (A.Yo),
      "vuelve"          : (A.El),
      "vuelven"         : (A.Ellos),
      "vuelves"         : (A.Tu),
      "vuelvo"          : (A.Yo),
      "véis"            : (A.Vosotros),
    };
  }

  static get Attributes() {
    return {
      Yo:        0x0001,
      Tu:        0x0002,
      El:        0x0004,
      Nosotros:  0x0008,
      Vosotros:  0x0010,
      Ellos:     0x0020,
    };
  }

  _nameToAttribute() {
    const A = this.constructor.Attributes;
    return {
      "yo" : (A.Yo),
      "tú" : (A.Tu),
      "él" : (A.El),
      "nosotros" : (A.Nosotros),
      "vosotros" : (A.Vosotros),
      "ellos" : (A.Ellos),
      "usted" : (A.El),
      "ustedes" : (A.Ellos),
      "ella" : (A.El),
      "ellas" : (A.Ellos),
      "nosotras" : (A.Nosotros),
      "vosotras" : (A.Vosotros),
    };
  }

  orderedNames() {
    return [
      "yo",
      "tú",
      "él",
      "nosotros",
      "vosotros",
      "ellos",
      "usted",
      "ustedes",
      "ella",
      "ellas",
      "nosotras",
      "vosotras",
    ];
  }

  _attributeForLevel(level) {
    const names = this.orderedNames();
    const idx = level % names.length;
    const subject = names[idx];
    const map = this._nameToAttribute();
    return map[subject] || 0;
  }

  _subjectForLevel(level) {
    const names = this.orderedNames();
    return names[level % names.length];
  }

  _ensureCaches() {
    const C = this.constructor;
    if (!C._matchingCache) C._matchingCache = new Map();
    if (!C._nonMatchingCache) C._nonMatchingCache = new Map();
  }

  generateMatchingValuesForLevel(level) {
    this._ensureCaches();
    const C = this.constructor;
    if (C._matchingCache.has(level)) {
      // return a shallow copy to avoid accidental external mutation
      return C._matchingCache.get(level).slice();
    }

    const attr = this._attributeForLevel(level);
    const dict = C._wordDict();
    const matches = [];

    for (const [word, flags] of Object.entries(dict)) {
      if ((flags & attr) !== 0) matches.push(word);
    }

    // cache a frozen copy to protect stability
    C._matchingCache.set(level, Object.freeze(matches.slice()));
    return matches;
  }

  generateNonMatchingValuesForLevel(level) {
    this._ensureCaches();
    const C = this.constructor;
    if (C._nonMatchingCache.has(level)) {
      return C._nonMatchingCache.get(level).slice();
    }

    const attr = this._attributeForLevel(level);
    const dict = C._wordDict();
    const nonMatches = [];

    for (const [word, flags] of Object.entries(dict)) {
      if ((flags & attr) === 0) nonMatches.push(word);
    }

    C._nonMatchingCache.set(level, Object.freeze(nonMatches.slice()));
    return nonMatches;
  }

  titleForLevel(level) {
    const subject = this._subjectForLevel(level);
    const title = `${subject} _____`;
    return title;
  }

  failureStringForValue(level, value) {
    const subject = this._subjectForLevel(level);
    return `Incorrecto:\n${subject} ${value}`;
  }
}

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { GameGenerator_SpanishVerbs };
}

if (typeof GameGenerators_classes !== 'undefined') {
  GameGenerators_classes["GameGenerator_SpanishVerbs"] = GameGenerator_SpanishVerbs;
}
