/*
Author: memalign
Title: Animal Wolfer
Description: "For levels, cycle through the following categories.

Here are the categories with their word list.

The matching values for a level are the words in the word list for the category. The non-matching values are all other words in other word lists that are NOT also in the matching list. Note that words may appear in multiple lists.

Insects:
ant
bee
butterfly
cockroach
cricket
dragonfly
firefly
flea
fly
grasshopper
horsefly
ladybug
mosquito
moth
stinkbug
termite
wasp
water bug

Birds:
blue jay
bluebird
cardinal
chicken
crow
dove
duck
eagle
goose
hawk
ostrich
owl
parrot
peacock
pelican
penguin
pigeon
robin
seagull
sparrow
stork
swan
turkey
vulture
woodpecker

Dinosaurs:
allosaurus
diplodocus
iguanodon
stegosaurus
triceratops
tyrannosaurus

Animals with feathers:
blue jay
bluebird
cardinal
chicken
crow
dove
duck
eagle
goose
hawk
ostrich
owl
parrot
peacock
pelican
penguin
pigeon
robin
seagull
sparrow
stork
swan
turkey
vulture
woodpecker

Animals with fur or hair:
baboon
bat
bear
beaver
bobcat
cat
chimpanzee
chipmunk
clouded leopard
cougar
cow
coyote
deer
dog
donkey
elephant
elk
fox
giraffe
goat
gorilla
guinea pig
hamster
hare
horse
kangaroo
koala
leopard
lion
mole
moose
mouse
otter
rabbit
raccoon
rat
sheep
skunk
snow leopard
squirrel
tiger
wolf
woodchuck
zebra

Four-legged animals:
alligator
beaded lizard
bear
beaver
bobcat
cat
chipmunk
clouded leopard
cougar
cow
coyote
crocodile
deer
dog
donkey
elephant
elk
fence lizard
fox
frog
giraffe
goat
guinea pig
hamster
hare
horned lizard
horse
koala
leopard
lion
mole
moose
mouse
mud puppy
newt
otter
pig
rabbit
raccoon
rat
salamander
sheep
skunk
snow leopard
squirrel
tiger
toad
turtle
wolf
woodchuck
zebra

Animals with wings:
bat
bee
blue jay
bluebird
butterfly
cardinal
chicken
cockroach
cricket
crow
dove
dragonfly
duck
eagle
firefly
fly
goose
grasshopper
hawk
horsefly
ladybug
mosquito
moth
ostrich
owl
parrot
peacock
pelican
pigeon
robin
seagull
sparrow
stinkbug
stork
swan
termite
turkey
vulture
wasp
woodpecker

Animals that live in water:
blue whale
clam
cod
crab
dolphin
flounder
goldfish
gray whale
guppy
humpback whale
killer whale
lobster
porpoise
right whale
salmon
shark
shrimp
swordfish
trout
tuna"
Date Created: 2025-11-21
Generated by: Copilot (Microsoft)
*/

class GameGenerator_Animals extends MAGameGenerator {
  constructor() {
    super();
    this.categories = [
      {
        name: "Insects",
        words: [
          "ant","bee","butterfly","cockroach","cricket","dragonfly","firefly","flea","fly",
          "grasshopper","horsefly","ladybug","mosquito","moth","stinkbug","termite","wasp","water bug"
        ]
      },
      {
        name: "Birds",
        words: [
          "blue jay","bluebird","cardinal","chicken","crow","dove","duck","eagle","goose","hawk",
          "ostrich","owl","parrot","peacock","pelican","penguin","pigeon","robin","seagull","sparrow",
          "stork","swan","turkey","vulture","woodpecker"
        ]
      },
      {
        name: "Dinosaurs",
        words: [
          "allosaurus","diplodocus","iguanodon","stegosaurus","triceratops","tyrannosaurus"
        ]
      },
      {
        name: "Animals with feathers",
        words: [
          "blue jay","bluebird","cardinal","chicken","crow","dove","duck","eagle","goose","hawk",
          "ostrich","owl","parrot","peacock","pelican","penguin","pigeon","robin","seagull","sparrow",
          "stork","swan","turkey","vulture","woodpecker"
        ]
      },
      {
        name: "Animals with fur or hair",
        words: [
          "baboon","bat","bear","beaver","bobcat","cat","chimpanzee","chipmunk","clouded leopard","cougar",
          "cow","coyote","deer","dog","donkey","elephant","elk","fox","giraffe","goat","gorilla","guinea pig",
          "hamster","hare","horse","kangaroo","koala","leopard","lion","mole","moose","mouse","otter","rabbit",
          "raccoon","rat","sheep","skunk","snow leopard","squirrel","tiger","wolf","woodchuck","zebra"
        ]
      },
      {
        name: "Four-legged animals",
        words: [
          "alligator","beaded lizard","bear","beaver","bobcat","cat","chipmunk","clouded leopard","cougar","cow",
          "coyote","crocodile","deer","dog","donkey","elephant","elk","fence lizard","fox","frog","giraffe","goat",
          "guinea pig","hamster","hare","horned lizard","horse","koala","leopard","lion","mole","moose","mouse",
          "mud puppy","newt","otter","pig","rabbit","raccoon","rat","salamander","sheep","skunk","snow leopard",
          "squirrel","tiger","toad","turtle","wolf","woodchuck","zebra"
        ]
      },
      {
        name: "Animals with wings",
        words: [
          "bat","bee","blue jay","bluebird","butterfly","cardinal","chicken","cockroach","cricket","crow","dove",
          "dragonfly","duck","eagle","firefly","fly","goose","grasshopper","hawk","horsefly","ladybug","mosquito",
          "moth","ostrich","owl","parrot","peacock","pelican","pigeon","robin","seagull","sparrow","stinkbug",
          "stork","swan","termite","turkey","vulture","wasp","woodpecker"
        ]
      },
      {
        name: "Animals that live in water",
        words: [
          "blue whale","clam","cod","crab","dolphin","flounder","goldfish","gray whale","guppy","humpback whale",
          "killer whale","lobster","porpoise","right whale","salmon","shark","shrimp","swordfish","trout","tuna"
        ]
      }
    ];

    // Flatten all words across categories for non-matching calculation
    this.allWords = [...new Set(this.categories.flatMap(c => c.words))];
  }

  gameName() {
    return "Animal Wolfer";
  }

  generateMatchingValuesForLevel(level) {
    const category = this.categories[level % this.categories.length];
    return category.words;
  }

  generateNonMatchingValuesForLevel(level) {
    const category = this.categories[level % this.categories.length];
    return this.allWords.filter(word => !category.words.includes(word));
  }

  titleForLevel(level) {
    const category = this.categories[level % this.categories.length];
    return category.name;
  }

  failureStringForValue(level, value) {
    const category = this.categories[level % this.categories.length];
    const singularCategory = this.depluralizeCategory(category.name);
    return `${this.capitalize(value)} is not ${this.articleize(singularCategory)}`;
  }

  // Helper to capitalize the first letter of the value
  capitalize(str) {
    if (!str || str.length === 0) return str;
    return str.charAt(0).toUpperCase() + str.slice(1);
  }

  // Helper to add "an"/"a" before category names when needed
  articleize(str) {
    const vowels = ["a","e","i","o","u"];
    const firstLetter = str.trim().charAt(0).toLowerCase();
    if (vowels.includes(firstLetter)) {
      return `an ${str.toLowerCase()}`;
    } else {
      return `a ${str.toLowerCase()}`;
    }
  }

  // Helper to de-pluralize certain category names
  depluralizeCategory(name) {
    // Special cases
    if (name.toLowerCase() === "insects") return "insect";
    if (name.toLowerCase().startsWith("animals")) {
      // Replace "Animals" with "Animal"
      return name.replace(/^Animals/i, "Animal");
    }
    return name;
  }

  isHunterBotAvailableOnLevel(level) {
    return level > 0;
  }
}

// export as module and register if required
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { GameGenerator_Animals };
}

if (typeof GameGenerators_classes !== 'undefined') {
  GameGenerators_classes["GameGenerator_Animals"] = GameGenerator_Animals;
}
