class GameGenerator_SpanishNouns extends MAGameGenerator {

  constructor() {
    super();
  }

  gameName() {
    return "Spanish Wolfer: Nouns";
  }

  static get Attributes() {
    return {
      ElRegular:   0x0001,
      La:          0x0002,
      Los:         0x0004,
      Las:         0x0008,
      ElIrregular: 0x0010,
      LaIrregular: 0x0020,
    };
  }

  static get wordDict() {
    if (this._wordDict) return this._wordDict;

    const A = this.Attributes;
    this._wordDict = {
      "actrices"        : (A.Las),
      "actriz"          : (A.La),
      "aeropuerto"      : (A.ElRegular),
      "aeropuertos"     : (A.Los),
      "agua"            : (A.ElIrregular),
      "aguas"           : (A.Las),
      "ajedrez"         : (A.ElIrregular),
      "ajo"             : (A.ElRegular),
      "ajos"            : (A.Los),
      "alma"            : (A.ElIrregular),
      "almas"           : (A.Las),
      "altavoces"       : (A.Los),
      "altavoz"         : (A.ElIrregular),
      "amigo"           : (A.ElRegular),
      "amigos"          : (A.Los),
      "amistad"         : (A.La),
      "amistades"       : (A.Las),
      "anillo"          : (A.ElRegular),
      "anillos"         : (A.Los),
      "antifaces"       : (A.Los),
      "antifaz"         : (A.ElIrregular),
      "apartamento"     : (A.ElRegular),
      "apartamentos"    : (A.Los),
      "aprendices"      : (A.Los),
      "aprendiz"        : (A.ElIrregular),
      "aroma"           : (A.ElIrregular),
      "aromas"          : (A.Los),
      "arroces"         : (A.Los),
      "arroz"           : (A.ElIrregular),
      "artista"         : (A.LaIrregular|A.ElIrregular),
      "artistas"        : (A.Los|A.Las),
      "asma"            : (A.ElIrregular),
      "asmas"           : (A.Las),
      "ataúd"           : (A.ElIrregular),
      "ataúdes"         : (A.Los),
      "atleta"          : (A.LaIrregular|A.ElIrregular),
      "atletas"         : (A.Los|A.Las),
      "avestruces"      : (A.Los),
      "avestruz"        : (A.ElIrregular),
      "axioma"          : (A.ElIrregular),
      "axiomas"         : (A.Los),
      "ballena"         : (A.La),
      "ballenas"        : (A.Las),
      "banco"           : (A.ElRegular),
      "bancos"          : (A.Los),
      "barnices"        : (A.Los),
      "barniz"          : (A.ElIrregular),
      "base"            : (A.LaIrregular),
      "bases"           : (A.Las),
      "basura"          : (A.La),
      "basuras"         : (A.Las),
      "baño"            : (A.ElRegular),
      "baños"           : (A.Los),
      "biblioteca"      : (A.La),
      "bibliotecas"     : (A.Las),
      "blusa"           : (A.La),
      "blusas"          : (A.Las),
      "boca"            : (A.La),
      "bocas"           : (A.Las),
      "bosque"          : (A.ElRegular),
      "bosques"         : (A.Los),
      "brazo"           : (A.ElRegular),
      "brazos"          : (A.Los),
      "buda"            : (A.ElIrregular),
      "budas"           : (A.Los),
      "caballo"         : (A.ElRegular),
      "caballos"        : (A.Los),
      "cabeza"          : (A.La),
      "cabezas"         : (A.Las),
      "café"            : (A.ElRegular),
      "cafés"           : (A.Los),
      "calle"           : (A.LaIrregular),
      "calles"          : (A.Las),
      "camisa"          : (A.La),
      "camisas"         : (A.Las),
      "canciones"       : (A.Las),
      "canción"         : (A.La),
      "capa"            : (A.La),
      "capas"           : (A.Las),
      "capital"         : (A.LaIrregular|A.ElIrregular),
      "capitales"       : (A.Las),
      "cara"            : (A.La),
      "caras"           : (A.Las),
      "carisma"         : (A.ElIrregular),
      "carne"           : (A.LaIrregular),
      "carnes"          : (A.Las),
      "carro"           : (A.ElRegular),
      "carros"          : (A.Los),
      "cartero"         : (A.ElRegular),
      "carteros"        : (A.Los),
      "casa"            : (A.La),
      "casas"           : (A.Las),
      "cerdo"           : (A.ElRegular),
      "cerdos"          : (A.Los),
      "cerebro"         : (A.ElRegular),
      "cerebros"        : (A.Los),
      "charco"          : (A.ElRegular),
      "cheque"          : (A.ElRegular),
      "cheques"         : (A.Los),
      "cielo"           : (A.ElRegular),
      "cielos"          : (A.Los),
      "cine"            : (A.ElRegular),
      "cines"           : (A.Los),
      "cintura"         : (A.La),
      "cinturas"        : (A.Las),
      "ciudad"          : (A.La),
      "ciudades"        : (A.Las),
      "clase"           : (A.LaIrregular),
      "clases"          : (A.Las),
      "clave"           : (A.LaIrregular),
      "claves"          : (A.Las),
      "clima"           : (A.ElIrregular),
      "climas"          : (A.Los),
      "cocina"          : (A.La),
      "cocinas"         : (A.Las),
      "codo"            : (A.ElRegular),
      "codos"           : (A.Los),
      "colegio"         : (A.ElRegular),
      "colegios"        : (A.Los),
      "coliflor"        : (A.LaIrregular),
      "coliflores"      : (A.Las),
      "colina"          : (A.La),
      "colinas"         : (A.Las),
      "coma"            : (A.LaIrregular|A.ElIrregular),
      "comas"           : (A.Los|A.Las),
      "cometa"          : (A.ElIrregular),
      "cometas"         : (A.Los),
      "computadora"     : (A.La),
      "computadoras"    : (A.Las),
      "conversaciones"  : (A.Las),
      "conversación"    : (A.La),
      "corazones"       : (A.Los),
      "corazón"         : (A.ElIrregular),
      "correa"          : (A.La),
      "correas"         : (A.Las),
      "corriente"       : (A.LaIrregular),
      "corrientes"      : (A.Las),
      "corte"           : (A.LaIrregular|A.ElIrregular),
      "cortes"          : (A.Los|A.Las),
      "costumbre"       : (A.La),
      "costumbres"      : (A.Las),
      "cruces"          : (A.Las),
      "cruz"            : (A.LaIrregular),
      "cuarto"          : (A.ElRegular),
      "cuartos"         : (A.Los),
      "cuchillo"        : (A.ElRegular),
      "cuchillos"       : (A.Los),
      "cuello"          : (A.ElRegular),
      "cuellos"         : (A.Los),
      "cuenta"          : (A.La),
      "cuentas"         : (A.Las),
      "cuestas"         : (A.Las),
      "cura"            : (A.LaIrregular|A.ElIrregular),
      "curas"           : (A.Los|A.Las),
      "cálices"         : (A.Los),
      "cáliz"           : (A.ElIrregular),
      "césped"          : (A.ElIrregular),
      "céspedes"        : (A.Los),
      "dedo"            : (A.ElRegular),
      "dedos"           : (A.Los),
      "destrucciones"   : (A.Las),
      "destrucción"     : (A.La),
      "diagrama"        : (A.ElIrregular),
      "diagramas"       : (A.Los),
      "diccionario"     : (A.ElRegular),
      "diccionarios"    : (A.Los),
      "dilema"          : (A.ElIrregular),
      "dilemas"         : (A.Los),
      "directoras"      : (A.Las),
      "directriz"       : (A.La),
      "disco"           : (A.LaIrregular),
      "discos"          : (A.Las),
      "discoteca"       : (A.La),
      "discotecas"      : (A.Las),
      "disfraces"       : (A.Los),
      "disfraz"         : (A.ElIrregular),
      "doctor"          : (A.ElRegular),
      "doctora"         : (A.La),
      "doctoras"        : (A.Las),
      "doctores"        : (A.Los),
      "dormitorio"      : (A.ElRegular),
      "dormitorios"     : (A.Los),
      "drama"           : (A.ElIrregular),
      "dramas"          : (A.Los),
      "día"             : (A.ElIrregular),
      "días"            : (A.Los),
      "edad"            : (A.La),
      "edades"          : (A.Las),
      "elefante"        : (A.ElRegular),
      "elefantes"       : (A.Los),
      "emperatrices"    : (A.Las),
      "emperatriz"      : (A.La),
      "enfermera"       : (A.La),
      "enfermeras"      : (A.Las),
      "enigma"          : (A.ElIrregular),
      "enigmas"         : (A.Los),
      "entrada"         : (A.La),
      "entradas"        : (A.Las),
      "equipaje"        : (A.ElRegular),
      "equipajes"       : (A.Los),
      "espalda"         : (A.La),
      "espaldas"        : (A.Las),
      "esquema"         : (A.ElIrregular),
      "esquemas"        : (A.Los),
      "estaciones"      : (A.Las),
      "estación"        : (A.La),
      "estadio"         : (A.ElRegular),
      "estadios"        : (A.Los),
      "estigma"         : (A.ElIrregular),
      "estigmas"        : (A.Los),
      "estimaciones"    : (A.Las),
      "estimación"      : (A.La),
      "estómago"        : (A.ElRegular),
      "estómagos"       : (A.Los),
      "examen"          : (A.ElRegular),
      "examenes"        : (A.Los),
      "faces"           : (A.Las),
      "facultad"        : (A.La),
      "facultades"      : (A.Las),
      "falda"           : (A.La),
      "faldas"          : (A.Las),
      "fantasma"        : (A.ElIrregular),
      "fantasmas"       : (A.Los),
      "farmacia"        : (A.La),
      "farmacias"       : (A.Las),
      "faz"             : (A.LaIrregular),
      "fe"              : (A.LaIrregular),
      "felicidad"       : (A.La),
      "felicidades"     : (A.Las),
      "fiebre"          : (A.LaIrregular),
      "fiebres"         : (A.Las),
      "final"           : (A.ElIrregular),
      "finales"         : (A.Los|A.Las),
      "flor"            : (A.LaIrregular),
      "flores"          : (A.Las),
      "florista"        : (A.LaIrregular|A.ElIrregular),
      "floristas"       : (A.Los|A.Las),
      "foto"            : (A.LaIrregular),
      "fotografía"      : (A.La),
      "fotografías"     : (A.Las),
      "fotos"           : (A.Las),
      "frase"           : (A.LaIrregular),
      "frases"          : (A.Las),
      "frente"          : (A.LaIrregular|A.ElIrregular),
      "frentes"         : (A.Los|A.Las),
      "fruta"           : (A.La),
      "frutas"          : (A.Las),
      "fuente"          : (A.LaIrregular),
      "fuentes"         : (A.Las),
      "fábrica"         : (A.La),
      "fábricas"        : (A.Las),
      "gallo"           : (A.ElRegular),
      "gallos"          : (A.Los),
      "gata"            : (A.La),
      "gatas"           : (A.Las),
      "gato"            : (A.ElRegular),
      "gatos"           : (A.Los),
      "gente"           : (A.LaIrregular),
      "gentes"          : (A.Las),
      "gorila"          : (A.ElIrregular),
      "gorilas"         : (A.Los),
      "guitarra"        : (A.La),
      "guitarras"       : (A.Las),
      "habla"           : (A.ElIrregular),
      "hada"            : (A.ElIrregular),
      "hadas"           : (A.Las),
      "hambre"          : (A.ElIrregular),
      "hambres"         : (A.Las),
      "hija"            : (A.La),
      "hijas"           : (A.Las),
      "hogar"           : (A.ElRegular),
      "hogares"         : (A.Los),
      "hombre"          : (A.ElRegular),
      "hombres"         : (A.Los),
      "hombro"          : (A.ElRegular),
      "hombros"         : (A.Los),
      "horno"           : (A.ElRegular),
      "hornos"          : (A.Los),
      "huésped"         : (A.ElIrregular),
      "huéspedes"       : (A.Los),
      "idioma"          : (A.ElIrregular),
      "idiomas"         : (A.Los),
      "iglesia"         : (A.La),
      "iglesias"        : (A.Las),
      "imagen"          : (A.LaIrregular),
      "imagenes"        : (A.Las),
      "incertidumbre"   : (A.La),
      "incertidumbres"  : (A.Las),
      "informaciones"   : (A.Las),
      "información"     : (A.La),
      "inquietud"       : (A.La),
      "inquietudes"     : (A.Las),
      "irritaciones"    : (A.Las),
      "irritación"      : (A.La),
      "jardines"        : (A.Los),
      "jardín"          : (A.ElRegular),
      "jurista"         : (A.LaIrregular|A.ElIrregular),
      "juristas"        : (A.Los|A.Las),
      "juventud"        : (A.La),
      "juventudes"      : (A.Las),
      "labores"         : (A.Las),
      "lago"            : (A.ElRegular),
      "lagos"           : (A.Los),
      "lapicero"        : (A.ElRegular),
      "lapiceros"       : (A.Los),
      "lecciones"       : (A.Las),
      "lección"         : (A.La),
      "leche"           : (A.LaIrregular),
      "leches"          : (A.Las),
      "legiones"        : (A.Las),
      "legión"          : (A.La),
      "legumbre"        : (A.La),
      "legumbres"       : (A.Las),
      "lentes"          : (A.Los),
      "leones"          : (A.Los),
      "león"            : (A.ElRegular),
      "libertad"        : (A.La),
      "libertades"      : (A.Las),
      "libro"           : (A.ElRegular),
      "libros"          : (A.Los),
      "llave"           : (A.LaIrregular),
      "llaves"          : (A.Las),
      "lluvia"          : (A.La),
      "lluvias"         : (A.Las),
      "lobo"            : (A.ElRegular),
      "lobos"           : (A.Los),
      "luces"           : (A.Las),
      "luz"             : (A.LaIrregular),
      "lápices"         : (A.Los),
      "lápiz"           : (A.ElIrregular),
      "madre"           : (A.La),
      "madres"          : (A.Las),
      "maestra"         : (A.La),
      "maestras"        : (A.Las),
      "mano"            : (A.LaIrregular),
      "manos"           : (A.Las),
      "mapa"            : (A.ElIrregular),
      "mapas"           : (A.Los),
      "matices"         : (A.Los),
      "matiz"           : (A.ElIrregular),
      "maíces"          : (A.Los),
      "maíz"            : (A.ElIrregular),
      "mediodía"        : (A.ElIrregular),
      "mediodías"       : (A.Los),
      "mente"           : (A.LaIrregular),
      "mentes"          : (A.Las),
      "mercado"         : (A.ElRegular),
      "mercados"        : (A.Los),
      "merced"          : (A.LaIrregular),
      "mesa"            : (A.La),
      "mesas"           : (A.Las),
      "miel"            : (A.LaIrregular),
      "mieles"          : (A.Las),
      "milord"          : (A.ElIrregular),
      "milords"         : (A.Los),
      "modelo"          : (A.LaIrregular|A.ElIrregular),
      "modelos"         : (A.Los|A.Las),
      "mono"            : (A.ElRegular),
      "monos"           : (A.Los),
      "montaña"         : (A.La),
      "montañas"        : (A.Las),
      "morfema"         : (A.ElIrregular),
      "morfemas"        : (A.Los),
      "moto"            : (A.LaIrregular),
      "motocicleta"     : (A.La),
      "motocicletas"    : (A.Las),
      "motos"           : (A.Las),
      "muerte"          : (A.LaIrregular),
      "muertes"         : (A.Las),
      "mujer"           : (A.La),
      "mujeres"         : (A.Las),
      "museo"           : (A.ElRegular),
      "museos"          : (A.Los),
      "muñeca"          : (A.La),
      "muñecas"         : (A.Las),
      "narices"         : (A.Las),
      "nariz"           : (A.LaIrregular),
      "nieve"           : (A.LaIrregular),
      "nieves"          : (A.Las),
      "niña"            : (A.La),
      "niñas"           : (A.Las),
      "niño"            : (A.ElRegular),
      "niños"           : (A.Los),
      "noche"           : (A.LaIrregular),
      "noches"          : (A.Las),
      "noticiones"      : (A.Los),
      "notición"        : (A.ElIrregular),
      "nube"            : (A.LaIrregular),
      "nubes"           : (A.Las),
      "nueces"          : (A.Las),
      "nuez"            : (A.LaIrregular),
      "océano"          : (A.ElRegular),
      "océanos"         : (A.Los),
      "oficina"         : (A.La),
      "oficinas"        : (A.Las),
      "ojo"             : (A.ElRegular),
      "ojos"            : (A.Los),
      "orden"           : (A.LaIrregular|A.ElIrregular),
      "oso"             : (A.ElRegular),
      "osos"            : (A.Los),
      "paces"           : (A.Las),
      "palabra"         : (A.La),
      "palabras"        : (A.Las),
      "panda"           : (A.ElIrregular),
      "pandas"          : (A.Los),
      "papa"            : (A.LaIrregular|A.ElIrregular),
      "papas"           : (A.Los|A.Las),
      "papel"           : (A.ElRegular),
      "papeles"         : (A.Los),
      "pared"           : (A.LaIrregular),
      "paredes"         : (A.Las),
      "parque"          : (A.ElRegular),
      "parques"         : (A.Los),
      "parte"           : (A.LaIrregular),
      "partes"          : (A.Las),
      "pasaporte"       : (A.ElRegular),
      "pasaportes"      : (A.Los),
      "paz"             : (A.LaIrregular),
      "país"            : (A.ElIrregular),
      "países"          : (A.Los),
      "peces"           : (A.Los),
      "pecho"           : (A.ElRegular),
      "pechos"          : (A.Los),
      "pelo"            : (A.ElRegular),
      "pelos"           : (A.Los),
      "pendiente"       : (A.LaIrregular|A.ElIrregular),
      "pendientes"      : (A.Los),
      "perra"           : (A.La),
      "perras"          : (A.Las),
      "perro"           : (A.ElRegular),
      "perros"          : (A.Los),
      "pez"             : (A.LaIrregular|A.ElIrregular),
      "pianista"        : (A.La),
      "pianistas"       : (A.Las),
      "pie"             : (A.ElRegular),
      "piel"            : (A.LaIrregular),
      "pieles"          : (A.Las),
      "pierna"          : (A.La),
      "piernas"         : (A.Las),
      "pies"            : (A.Los),
      "pijama"          : (A.La),
      "pijamas"         : (A.Las),
      "pila"            : (A.La),
      "pilas"           : (A.Las),
      "piscina"         : (A.La),
      "piscinas"        : (A.Las),
      "planeta"         : (A.ElIrregular),
      "planetas"        : (A.Los),
      "playa"           : (A.La),
      "playas"          : (A.Las),
      "precio"          : (A.ElRegular),
      "precios"         : (A.Los),
      "prisma"          : (A.ElIrregular),
      "prismas"         : (A.Los),
      "problema"        : (A.ElIrregular),
      "problemas"       : (A.Los),
      "profesiones"     : (A.Las),
      "profesión"       : (A.La),
      "profesora"       : (A.La),
      "profesoras"      : (A.Las),
      "programa"        : (A.ElIrregular),
      "programas"       : (A.Los),
      "puerta"          : (A.La),
      "puertas"         : (A.Las),
      "puerto"          : (A.ElRegular),
      "puertos"         : (A.Los),
      "radio"           : (A.ElRegular|A.LaIrregular),
      "radios"          : (A.Los|A.Las),
      "red"             : (A.LaIrregular),
      "redes"           : (A.Las),
      "refrigeradora"   : (A.La),
      "refrigeradores"  : (A.Los),
      "regiones"        : (A.Las),
      "región"          : (A.La),
      "religiones"      : (A.Las),
      "religión"        : (A.La),
      "renta"           : (A.La),
      "rentas"          : (A.Las),
      "restaurante"     : (A.ElRegular),
      "restaurantes"    : (A.Los),
      "rigideces"       : (A.Las),
      "rigidez"         : (A.La),
      "rosa"            : (A.La),
      "rosas"           : (A.Las),
      "récord"          : (A.ElIrregular),
      "río"             : (A.ElRegular),
      "ríos"            : (A.Los),
      "sal"             : (A.LaIrregular),
      "sala"            : (A.La),
      "salas"           : (A.Las),
      "sales"           : (A.Las),
      "salud"           : (A.La),
      "saludes"         : (A.Las),
      "sangre"          : (A.LaIrregular),
      "sed"             : (A.LaIrregular),
      "sedes"           : (A.Las),
      "sensateces"      : (A.Las),
      "sensatez"        : (A.La),
      "serpiente"       : (A.LaIrregular),
      "serpientes"      : (A.Las),
      "señor"           : (A.ElRegular),
      "señora"          : (A.La),
      "señoras"         : (A.Las),
      "señores"         : (A.Los),
      "silla"           : (A.La),
      "sillas"          : (A.Las),
      "sistema"         : (A.ElIrregular),
      "sistemas"        : (A.Los),
      "sociedad"        : (A.La),
      "sociedades"      : (A.Las),
      "sofá"            : (A.ElIrregular),
      "sofás"           : (A.Los),
      "sombrero"        : (A.ElRegular),
      "sombreros"       : (A.Los),
      "soprano"         : (A.LaIrregular|A.ElIrregular),
      "sopranos"        : (A.Las),
      "suerte"          : (A.LaIrregular),
      "tarde"           : (A.LaIrregular),
      "tardes"          : (A.Las),
      "teatro"          : (A.ElRegular),
      "teatros"         : (A.Los),
      "tele"            : (A.LaIrregular),
      "teles"           : (A.Las),
      "televisiones"    : (A.Las),
      "televisión"      : (A.La),
      "tema"            : (A.ElIrregular),
      "temas"           : (A.Los),
      "templo"          : (A.ElRegular),
      "templos"         : (A.Los),
      "tensiones"       : (A.Las),
      "tensión"         : (A.La),
      "tigre"           : (A.ElRegular),
      "tigres"          : (A.Los),
      "torre"           : (A.LaIrregular),
      "torres"          : (A.Las),
      "tranvía"         : (A.ElIrregular),
      "tranvías"        : (A.Los),
      "tribu"           : (A.LaIrregular),
      "tribus"          : (A.Las),
      "tío"             : (A.ElRegular),
      "tíos"            : (A.Los),
      "universidad"     : (A.La),
      "universidades"   : (A.Las),
      "vaca"            : (A.La),
      "vacas"           : (A.Las),
      "validez"         : (A.La),
      "vejez"           : (A.La),
      "ventana"         : (A.La),
      "ventanas"        : (A.Las),
      "vestido"         : (A.ElRegular),
      "vestidos"        : (A.Los),
      "virtud"          : (A.La),
      "virtudes"        : (A.Las),
      "voces"           : (A.Las),
      "voz"             : (A.LaIrregular),
      "yoga"            : (A.ElIrregular),
      "yogas"           : (A.Los),
      "zapato"          : (A.ElRegular),
      "zapatos"         : (A.Los),
      "ángel"           : (A.ElRegular),
      "ángeles"         : (A.Los),
      "órdenes"         : (A.Los|A.Las),
    };

    return this._wordDict;
  }

  static attributeForLevel(level) {
    const order = [
      this.Attributes.ElRegular,
      this.Attributes.La,
      this.Attributes.Los,
      this.Attributes.Las,
      this.Attributes.ElRegular | this.Attributes.ElIrregular,
      this.Attributes.La | this.Attributes.LaIrregular,
    ];
    return order[level % order.length];
  }

  titleForLevel(level) {
    const attr = this.constructor.attributeForLevel(level);
    const A = this.constructor.Attributes;
    if ((attr & A.ElRegular) !== 0) return "el _____";
    if ((attr & A.La) !== 0) return "la _____";
    if ((attr & A.Los) !== 0) return "los _____";
    if ((attr & A.Las) !== 0) return "las _____";
    return "";
  }

  generateMatchingValuesForLevel(level) {
    const attr = this.constructor.attributeForLevel(level);
    const dict = this.constructor.wordDict;
    const matches = [];
    for (const [word, flags] of Object.entries(dict)) {
      if ((flags & attr) !== 0) matches.push(word);
    }
    return matches;
  }

  generateNonMatchingValuesForLevel(level) {
    let attr = this.constructor.attributeForLevel(level);
    const A = this.constructor.Attributes;
    if (attr === A.ElRegular) {
      attr = attr | A.ElIrregular; // don't punish the user for choosing irregular words
    } else if (attr === A.La) {
      attr = attr | A.LaIrregular;
    }

    const dict = this.constructor.wordDict;
    const nonMatches = [];
    for (const [word, flags] of Object.entries(dict)) {
      if ((flags & attr) === 0) nonMatches.push(word);
    }
    return nonMatches;
  }

  failureStringForValue(level, value) {
    const roundName = this.titleForLevel(level).split(" ")[0];
    return `Incorrecto:\n${roundName} ${value}`;
  }
}

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { GameGenerator_SpanishNouns };
}

if (typeof GameGenerators_classes !== 'undefined') {
  GameGenerators_classes["GameGenerator_SpanishNouns"] = GameGenerator_SpanishNouns;
}
