// Author: anonymous
// Title: PokéPrescription
// Description: "Every level’s goal should be “Pokémon names” or “Medication names”, alternating.
// For medication names, use the names of prescription medications.
// Have at least 200 Pokémon and 60 medication names.
// When the goal is Pokémon names, the non-matching values are the medication names. When the goal is medication names, the non-matching values are the Pokémon names."
// Date Created: November 20, 2025
// Generated by: Gemini (Google)

class GameGenerator_PokePrescription extends MAGameGenerator {
  constructor() {
    super();
    
    // Source lists for the game content
    // At least 200 Pokémon names (Source: Gen 1-4)
    this.pokemonNames = [
      "Bulbasaur", "Ivysaur", "Venusaur", "Charmander", "Charmeleon", "Charizard", "Squirtle", "Wartortle", "Blastoise", "Caterpie",
      "Metapod", "Butterfree", "Pidgey", "Pidgeotto", "Pidgeot", "Rattata", "Raticate", "Spearow", "Fearow", "Ekans",
      "Arbok", "Pikachu", "Raichu", "Sandshrew", "Sandslash", "Nidoran♀", "Nidorina", "Nidoqueen", "Nidoran♂", "Nidorino",
      "Nidoking", "Clefairy", "Clefable", "Vulpix", "Ninetales", "Jigglypuff", "Wigglytuff", "Zubat", "Golbat", "Oddish",
      "Gloom", "Vileplume", "Paras", "Parasect", "Venonat", "Venomoth", "Diglett", "Dugtrio", "Meowth", "Persian",
      "Psyduck", "Golduck", "Mankey", "Primeape", "Growlithe", "Arcanine", "Poliwag", "Poliwhirl", "Poliwrath", "Abra",
      "Kadabra", "Alakazam", "Machop", "Machoke", "Machamp", "Bellsprout", "Weepinbell", "Victreebel", "Tentacool", "Tentacruel",
      "Geodude", "Graveler", "Golem", "Ponyta", "Rapidash", "Slowpoke", "Slowbro", "Magnemite", "Magneton", "Farfetch'd",
      "Doduo", "Dodrio", "Seel", "Dewgong", "Grimer", "Muk", "Shellder", "Cloyster", "Gastly", "Haunter",
      "Gengar", "Onix", "Drowzee", "Hypno", "Krabby", "Kingler", "Voltorb", "Electrode", "Exeggcute", "Exeggutor",
      "Cubone", "Marowak", "Hitmonlee", "Hitmonchan", "Lickitung", "Koffing", "Weezing", "Rhyhorn", "Rhydon", "Chansey",
      "Tangela", "Kangaskhan", "Horsea", "Seadra", "Goldeen", "Seaking", "Staryu", "Starmie", "Mr. Mime", "Scyther",
      "Jynx", "Electabuzz", "Magmar", "Pinsir", "Tauros", "Magikarp", "Gyarados", "Lapras", "Ditto", "Eevee",
      "Vaporeon", "Jolteon", "Flareon", "Porygon", "Omanyte", "Omastar", "Kabuto", "Kabutops", "Aerodactyl", "Snorlax",
      "Articuno", "Zapdos", "Moltres", "Dratini", "Dragonair", "Dragonite", "Mewtwo", "Mew", "Chikorita", "Bayleef",
      "Meganium", "Cyndaquil", "Quilava", "Typhlosion", "Content", "Croconaw", "Feraligatr", "Sentret", "Furret", "Hoothoot",
      "Noctowl", "Ledyba", "Ledian", "Spinarak", "Ariados", "Crobat", "Chinchou", "Lanturn", "Pichu", "Cleffa",
      "Igglybuff", "Togepi", "Togetic", "Natu", "Xatu", "Mareep", "Flaaffy", "Ampharos", "Bellossom", "Marill",
      "Azumarill", "Sudowoodo", "Politoed", "Hoppip", "Skiploom", "Jumpluff", "Aipom", "Sunkern", "Sunflora", "Yanma",
      "Wooper", "Quagsire", "Espeon", "Umbreon", "Murkrow", "Slowking", "Misdreavus", "Unown", "Wobbuffet", "Girafarig",
      "Pineco", "Forretress", "Dunsparce", "Gligar", "Steelix", "Snubbull", "Granbull", "Qwilfish", "Scizor", "Shuckle",
      "Heracross", "Sneasel", "Teddiursa", "Ursaring", "Slugma", "Magcargo", "Swinub", "Piloswine", "Corsola", "Remoraid",
      "Octillery", "Delibird", "Mantine", "Skarmory", "Houndour", "Houndoom", "Kingdra", "Phanpy", "Donphan", "Porygon2",
      "Stantler", "Smeargle", "Tyrogue", "Hitmontop", "Smoochum", "Elekid", "Magby", "Miltank", "Blissey", "Raikou",
      "Entei", "Suicune", "Larvitar", "Pupitar", "Tyranitar", "Lugia", "Ho-Oh", "Celebi", "Treecko", "Grovyle",
      "Sceptile", "Torchic", "Combusken", "Blaziken", "Mudkip", "Marshtomp", "Swampert"
    ];

    // At least 60 prescription medication names (Brand or Generic)
    this.medicationNames = [
      "Lipitor", "Simvastatin", "Lisinopril", "Metformin", "Amoxicillin", "Levothyroxine", "Omeprazole", "Vicodin", "Zoloft", "Albuterol",
      "Hydrochlorothiazide", "Gabapentin", "Amlodipine", "Citalopram", "Furosemide", "Trazodone", "Pantoprazole", "Tramadol", "Warfarin", "Atorvastatin",
      "Metoprolol", "Losartan", "Azithromycin", "Prednisone", "Insulin", "Adderall", "Oxycodone", "Cephalexin", "Tamsulosin", "Clonazepam",
      "Meloxicam", "Montelukast", "Cyclobenzaprine", "Fluoxetine", "Bupropion", "Sertraline", "Venlafaxine", "Loratadine", "Doxycycline", "Naproxen",
      "Ciprofloxacin", "Ranitidine", "Aspirin", "Ibuprofen", "Duloxetine", "Tizanidine", "Ropinirole", "Pravastatin", "Escitalopram", "Rosuvastatin",
      "Carvedilol", "Quetiapine", "Risperidone", "Sildenafil", "Tadalafil", "Clopidogrel", "Phenytoin", "Valium", "Xanax", "Prozac",
      "Zithromax", "Viagra", "Cymbalta", "Lexapro", "Coumadin", "Diovan", "Plavix", "Wellbutrin", "Celexa", "Lyrica"
    ];
  }

  /**
   * Returns the game's title.
   * @returns {string} The game name.
   */
  gameName() {
    return "Wolfer: PokéPrescription";
  }

  /**
   * Determines the goal/condition for the level.
   * @param {number} level The current level number (0-indexed).
   * @returns {string} The title/goal for the level.
   */
  titleForLevel(level) {
    // Levels alternate between Pokémon (even levels: 0, 2, 4...) and Medication (odd levels: 1, 3, 5...)
    if (level % 2 === 0) {
      return "Pokémon names";
    } else {
      return "Medication names";
    }
  }

  /**
   * Generates the list of matching values for the level.
   * @param {number} level The current level number (0-indexed).
   * @returns {string[]} An array of strings that match the level condition.
   */
  generateMatchingValuesForLevel(level) {
    if (level % 2 === 0) {
      // Goal is Pokémon names
      return this.pokemonNames;
    } else {
      // Goal is Medication names
      return this.medicationNames;
    }
  }

  /**
   * Generates the list of non-matching values for the level.
   * @param {number} level The current level number (0-indexed).
   * @returns {string[]} An array of strings that do NOT match the level condition.
   */
  generateNonMatchingValuesForLevel(level) {
    if (level % 2 === 0) {
      // Goal is Pokémon names, non-matching are Medication names
      return this.medicationNames;
    } else {
      // Goal is Medication names, non-matching are Pokémon names
      return this.pokemonNames;
    }
  }

  /**
   * Provides a concise explanation for why a non-matching value is incorrect.
   * @param {number} level The current level number (0-indexed).
   * @param {string} value The non-matching value selected by the user.
   * @returns {string} A string explaining the failure.
   */
  failureStringForValue(level, value) {
    if (level % 2 === 0) {
      // Goal is Pokémon names, so the value is a medication name
      return `"${value}" is a medication, not a Pokémon name!`;
    } else {
      // Goal is Medication names, so the value is a Pokémon name
      return `"${value}" is a Pokémon, not a medication name!`;
    }
  }

  /**
   * Determines if the HunterBot should be present on the level.
   * @param {number} level The current level number (0-indexed).
   * @returns {boolean} True if HunterBot is available.
   */
  isHunterBotAvailableOnLevel(level) {
    // HunterBot won't show up on the first level
    return level > 0;
  }
}

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { GameGenerator_PokePrescription };
}

if (typeof GameGenerators_classes !== 'undefined') {
  GameGenerators_classes["GameGenerator_PokePrescription"] = GameGenerator_PokePrescription;
}
