/*
Author: memalign
Title: Morse Code Wolfer
Description: "On every level, the user must eat values that match any of three alphabet letters chosen for that level. The title of the level uses the alphabet like “Eat a, b, c”. All values are written in Morse code. Correct answers match the letters for the level. Incorrect answers are the rest of the letters of the alphabet."
Date Created: 2025-11-14
Generated by: ChatGPT (OpenAI)
*/

class GameGenerator_MorseCode extends MAGameGenerator {
  constructor() {
    super();

    // Standard A–Z Morse code mapping
    this.letters = "abcdefghijklmnopqrstuvwxyz".split("");
    this.morse = {
      a: ".-",    b: "-...",  c: "-.-.",  d: "-..",   e: ".",
      f: "..-.",  g: "--.",   h: "....",  i: "..",    j: ".---",
      k: "-.-",   l: ".-..",  m: "--",    n: "-.",    o: "---",
      p: ".--.",  q: "--.-",  r: ".-.",   s: "...",   t: "-",
      u: "..-",   v: "...-",  w: ".--",   x: "-..-",  y: "-.--",
      z: "--.."
    };
    // Build reverse lookup table
    this.inverseMorse = {};
    for (const key of Object.keys(this.morse)) {
      this.inverseMorse[this.morse[key]] = key;
    }
  }

  gameName() {
    return "Morse Code Wolfer";
  }

  // Deterministic selection: each level chooses 3 consecutive letters, wrapping at Z.
  _lettersForLevel(level) {
    const start = (level * 3) % 26;
    return [
      this.letters[start],
      this.letters[(start + 1) % 26],
      this.letters[(start + 2) % 26]
    ];
  }

  generateMatchingValuesForLevel(level) {
    const chosen = this._lettersForLevel(level);
    return chosen.map(l => this.morse[l]);
  }

  generateNonMatchingValuesForLevel(level) {
    const chosen = this._lettersForLevel(level);
    const remaining = this.letters.filter(l => !chosen.includes(l));
    return remaining.map(l => this.morse[l]);
  }

  titleForLevel(level) {
    const chosen = this._lettersForLevel(level);
    return `Eat ${chosen.join(", ")}`;
  }

  failureStringForValue(level, value) {
    const chosen = this._lettersForLevel(level);
    const decoded = this.inverseMorse[value] || "?";
    return `${decoded} (${value}) is not one of ${chosen.join(", ")}`;
  }

  isHunterBotAvailableOnLevel(level) {
    return level > 0;
  }
}

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { GameGenerator_MorseCode };
}

if (typeof GameGenerators_classes !== 'undefined') {
  GameGenerators_classes["GameGenerator_MorseCode"] = GameGenerator_MorseCode;
}
