const data = {
  food: {
    label: "Food",
    pinyinLabel: "Shíwù",
    chinese: "食物",
    words: [
      { word: "苹果", pinyin: "Píngguǒ", image: "🍎", english: "Apple" },
      { word: "面条", pinyin: "Miàntiáo", imageURL: "img/noodles.png", english: "Noodles" },
      { word: "番茄", pinyin: "Fānqié", image: "🍅", english: "Tomato" },
      { word: "香蕉", pinyin: "Xiāngjiāo", image: "🍌", english: "Banana" },
      { word: "柠檬", pinyin: "Níngméng", image: "🍋", english: "Lemon" },
      { word: "米饭", pinyin: "Mǐfàn", image: "🍚", english: "Rice" },
      { word: "面包", pinyin: "Miànbāo", image: "🍞", english: "Bread" },
      { word: "鸡蛋", pinyin: "Jīdàn", image: "🥚", english: "Egg" },
      { word: "牛奶", pinyin: "Niúnǎi", image: "🥛", english: "Milk" },
      { word: "奶酪", pinyin: "Nǎilào", image: "🧀", english: "Cheese" },
      { word: "咖啡", pinyin: "Kāfēi", image: "☕", english: "Coffee" },
      { word: "水", pinyin: "Shuǐ", imageURL: "img/water.png", english: "Water" },
      { word: "茶", pinyin: "Chá", image: "🍵", english: "Tea" },
      { word: "鱼", pinyin: "Yú", image: "🐟", english: "Fish" },
      { word: "鸡肉", pinyin: "Jīròu", image: "🍗", english: "Chicken" },
      { word: "冰淇淋", pinyin: "Bīngqílín", image: "🍦", english: "Ice Cream" },
      { word: "棒冰", pinyin: "Bàngbīng", imageURL: "img/popsicle.png", english: "Popsicle" },
      { word: "草莓", pinyin: "Cǎoméi", image: "🍓", english: "Strawberry" },
      { word: "桔子", pinyin: "Júzi", image: "🍊", english: "Orange" },
      { word: "樱桃", pinyin: "Yīngtáo", image: "🍒", english: "Cherry" },
      { word: "西兰花", pinyin: "Xīlánhuā", image: "🥦", english: "Broccoli" },
      { word: "白菜", pinyin: "Báicài", imageURL: "img/bokchoy.jpg", english: "Bok Choy" },
      { word: "胡萝卜", pinyin: "Húluóbo", image: "🥕", english: "Carrot" },
      { word: "玉米", pinyin: "Yùmǐ", image: "🌽", english: "Corn" },
      { word: "芹菜", pinyin: "Qíncài", imageURL: "img/celery.png", english: "Celery" },
      { word: "蘑菇", pinyin: "Mógū", image: "🍄‍🟫", english: "Mushroom" },
      { word: "黄瓜", pinyin: "Huángguā", image: "🥒", english: "Cucumber" },
      { word: "蛋糕", pinyin: "Dàngāo", image: "🍰", english: "Cake" },
      { word: "披萨", pinyin: "Pīsà", image: "🍕", english: "Pizza" },
      { word: "意大利面", pinyin: "Yìdàlì miàn", image: "🍝", english: "Spaghetti" },
      { word: "四季豆", pinyin: "Sìjìdòu", imageURL: "img/greenbean.jpg", english: "Green bean" },
      { word: "西瓜", pinyin: "Xīguā", image: "🍉", english: "Watermelon" },
      { word: "糖", pinyin: "Táng", imageURL: "img/sugar.png", english: "Sugar" },
      { word: "三明治", pinyin: "Sānmíngzhì", image: "🥪", english: "Sandwich" },
      { word: "水果", pinyin: "Shuǐguǒ", imageURL: "img/fruit.png", english: "Fruit" },
    ]
  },
  utensils: {
    label: "Utensils",
    pinyinLabel: "Cānjù",
    chinese: "餐具",
    words: [
      { word: "叉子", pinyin: "Chāzi", imageURL: "img/fork.png", english: "Fork" },
      { word: "刀", pinyin: "Dāo", imageURL: "img/knife.png", english: "Knife" },
      { word: "勺子", pinyin: "Sháozi", image: "🥄", english: "Spoon" },
      { word: "筷子", pinyin: "Kuàizi", image: "🥢", english: "Chopsticks" },
      { word: "碗", pinyin: "Wǎn", imageURL: "img/bowl.png", english: "Bowl" },
      { word: "盘子", pinyin: "Pánzi", imageURL: "img/plate.png", english: "Plate" },
      { word: "杯子", pinyin: "Bēizi", imageURL: "img/cup.png", english: "Cup" },
    ]
  },
  household: {
    label: "Household",
    pinyinLabel: "Jiāshì",
    chinese: "家事",
    words: [
      { word: "桌子", pinyin: "Zhuōzi", imageURL: "img/table.png", english: "Table" },
      { word: "椅子", pinyin: "Yǐzi", image: "🪑", english: "Chair" },
      { word: "灯", pinyin: "Dēng", image: "💡", english: "Light" },
      { word: "床", pinyin: "Chuáng", image: "🛏️", english: "Bed" },
      { word: "窗户", pinyin: "Chuānghù", image: "🪟", english: "Window" },
      { word: "被子", pinyin: "Bèizi", imageURL: "img/blanket.png", english: "Blanket" },
      { word: "门", pinyin: "Mén", image: "🚪", english: "Door" },
      { word: "钥匙", pinyin: "Yàoshi", image: "🔑", english: "Keys" },
      { word: "冰箱", pinyin: "Bīngxiāng", imageURL: "img/fridge.png", english: "Fridge" },
      { word: "冰柜", pinyin: "Bīngguì", imageURL: "img/freezer.png", english: "Freezer" },
      { word: "沙发", pinyin: "Shāfā", image: "🛋️", english: "Sofa" },
      { word: "书", pinyin: "Shū", imageURL: "img/book.png", english: "Book" },
      { word: "肥皂", pinyin: "Féizào", image: "🧼", english: "Soap" },
      { word: "洗发水", pinyin: "Xǐfàshuǐ", imageURL: "img/shampoo.png", english: "Shampoo" },
      { word: "毛巾", pinyin: "Máojīn", imageURL: "img/towel.png", english: "Towel" },
      { word: "洗澡", pinyin: "Xǐzǎo", image: "🚿", english: "Shower" },
      { word: "水道", pinyin: "Shuǐdào", imageURL: "img/drain.png", english: "Drain" },
      { word: "厕所", pinyin: "Cèsuǒ", image: "🚽", english: "Toilet" },
      { word: "餐巾", pinyin: "Cānjīn", imageURL: "img/napkin.png", english: "Napkin" },
      { word: "纸巾", pinyin: "Zhǐjīn", imageURL: "img/tissue.png", english: "Tissue" },
    { word: "鼻涕", pinyin: "Bítì", imageURL: "img/snot.png", english: "Snot" },
      { word: "垃圾", pinyin: "Lājī", image: "🗑️", english: "Trash" },
      { word: "眼镜", pinyin: "Yǎnjìng", image: "👓", english: "Glasses" },
      { word: "电脑", pinyin: "Diànnǎo", image: "💻", english: "Computer" },
      { word: "耳机", pinyin: "Ěrjī", image: "🎧", english: "Headphones" },
      { word: "耳塞", pinyin: "Ěrsāi", imageURL: "img/earprotection.png", english: "Ear Protection" },
      { word: "厨房", pinyin: "Chúfáng", imageURL: "img/kitchen.png", english: "Kitchen" },
      { word: "锅", pinyin: "Guō", imageURL: "img/pot.png", english: "Pot" },
      { word: "平底锅", pinyin: "Píngdǐguō", imageURL: "img/pan.png", english: "Pan" },
      { word: "炉子", pinyin: "Lúzi", imageURL: "img/stove.png", english: "Stove" },
      { word: "烤箱", pinyin: "Kǎoxiāng", imageURL: "img/oven.png", english: "Oven" },
      { word: "吸尘器", pinyin: "Xīchénqì", imageURL: "img/vacuum.png", english: "Vacuum" },
      { word: "钱", pinyin: "Qián", image: "💵", english: "Money" },
      { word: "电视", pinyin: "Diànshì", image: "📺", english: "TV" },
      { word: "电视节目", pinyin: "Diànshì Jiémù", imageURL: "img/tvshow.png", english: "TV Show" },
      { word: "歌", pinyin: "Gē", image: "🎵", english: "Song" },
      { word: "篮子", pinyin: "Lánzi", image: "🧺", english: "Basket" },
      { word: "玩具", pinyin: "Wánjù", imageURL: "img/toy.png", english: "Toy" },
    ]
  },
	routines: {
		label: "Routines",
		pinyinLabel: "Rìcháng",
		chinese: "日常",
		words: [
			{ word: "刷牙", pinyin: "Shuāyá", imageURL: "img/brushteeth.png", english: "Brush teeth" },
			{ word: "吃早餐", pinyin: "Chī zǎocān", imageURL: "img/eatbreakfast.png", english: "Eat breakfast" },
			{ word: "吃午饭", pinyin: "Chī wǔfàn", imageURL: "img/eatlunch.png", english: "Eat lunch" },
			{ word: "吃晚饭", pinyin: "Chī wǎnfàn", imageURL: "img/eatdinner.png", english: "Eat dinner" },
      { word: "零食", pinyin: "Língshí", imageURL: "img/snack.png", english: "Snack" },
			{ word: "起床", pinyin: "Qǐchuáng", imageURL: "img/wakeup.png", english: "Wake up" },
			{ word: "上班", pinyin: "Shàngbān", imageURL: "img/gotowork.png", english: "Go to work" },
			{ word: "下班", pinyin: "Xiàbān", imageURL: "img/finishwork.png", english: "Finish work" },
			{ word: "午睡时间", pinyin: "Wǔshuì shíjiān", imageURL: "img/naptime.png", english: "Nap time" },
			{ word: "睡觉时间", pinyin: "Shuìjiào shíjiān", imageURL: "img/bedtime.png", english: "Bedtime" },
      { word: "牙线", pinyin: "Yáxiàn", imageURL: "img/floss.png", english: "Floss" },
      { word: "漱口", pinyin: "Shùkǒu", imageURL: "img/swish.png", english: "Swish" },
      { word: "药", pinyin: "Yào", image: "💊", english: "Medicine" },
      { word: "乳液", pinyin: "Rǔyè", image: "🧴", english: "Lotion" },
      { word: "洗衣服", pinyin: "Xǐ yīfu", imageURL: "img/laundry.png", english: "Laundry" },
      { word: "脏衣服", pinyin: "Zāng yīfu", imageURL: "img/dirtylaundry.png", english: "Dirty laundry" },
      { word: "闪卡", pinyin: "Shǎnkǎ", imageURL: "cards/cards.png", english: "Flashcard" },
		]
	},
  emotions: {
    label: "Emotions",
    pinyinLabel: "Qínggǎn",
    chinese: "情感",
    words: [
      { word: "快乐", pinyin: "Kuàilè", image: "😊", english: "Happy" },
      { word: "难过", pinyin: "Nánguò", image: "😢", english: "Sad" },
      { word: "生气", pinyin: "Shēngqì", image: "😡", english: "Angry" },
      { word: "惊讶", pinyin: "Jīngyà", image: "😮", english: "Surprised" },
      { word: "害怕", pinyin: "Hàipà", imageURL: "img/afraid.png", english: "Afraid" },
      { word: "兴奋", pinyin: "Xīngfèn", imageURL: "img/excited.png", english: "Excited" },
      { word: "累", pinyin: "Lèi", image: "🥱", english: "Tired" },
      { word: "担心", pinyin: "Dānxīn", imageURL: "img/worried.png", english: "Worried" },
      { word: "轻松", pinyin: "Qīngsōng", imageURL: "img/relaxed.png", english: "Relaxed" },
      { word: "无聊", pinyin: "Wúliáo", imageURL: "img/bored.png", english: "Bored" },
    ]
  },
  numbers: {
    label: "Numbers",
    pinyinLabel: "Shùzì",
    chinese: "数字",
    words: [
      { word: "一", pinyin: "Yī", image: "1️⃣", english: "One" },
      { word: "二", pinyin: "Èr", image: "2️⃣", english: "Two" },
      { word: "三", pinyin: "Sān", image: "3️⃣", english: "Three" },
      { word: "四", pinyin: "Sì", image: "4️⃣", english: "Four" },
      { word: "五", pinyin: "Wǔ", image: "5️⃣", english: "Five" },
      { word: "六", pinyin: "Liù", image: "6️⃣", english: "Six" },
      { word: "七", pinyin: "Qī", image: "7️⃣", english: "Seven" },
      { word: "八", pinyin: "Bā", image: "8️⃣", english: "Eight" },
      { word: "九", pinyin: "Jiǔ", image: "9️⃣", english: "Nine" },
      { word: "十", pinyin: "Shí", image: "🔟", english: "Ten" },
      { word: "二十", pinyin: "Èrshí", image: "20", english: "20" },
      { word: "三十", pinyin: "Sānshí", image: "30", english: "30" },
      { word: "四十", pinyin: "Sìshí", image: "40", english: "40" },
      { word: "一百", pinyin: "Yībǎi", image: "100", english: "100" },
    ]
  },
  time: {
    label: "Time",
    pinyinLabel: "Shíjiān",
    chinese: "时间",
    image: "📆",
    words: [
      { word: "分钟", pinyin: "Fēnzhōng", imageURL: "img/minute.png", english: "Minutes" },
      { word: "小时", pinyin: "Xiǎoshí", imageURL: "img/hour.png", english: "Hours" },
      { word: "天", pinyin: "Tiān", imageURL: "img/day.png", english: "Day" },
      { word: "星期", pinyin: "Xīngqī", imageURL: "img/week.png", english: "Week" },
      { word: "月", pinyin: "Yuè", imageURL: "img/month.png", english: "Month" },
      { word: "今天", pinyin: "Jīntiān", imageURL: "img/today.png", english: "Today" },
      { word: "昨天", pinyin: "Zuótiān", imageURL: "img/yesterday.png", english: "Yesterday" },
      { word: "明天", pinyin: "Míngtiān", imageURL: "img/tomorrow.png", english: "Tomorrow" },
      { word: "现在", pinyin: "Xiànzài", imageURL: "img/now.png", english: "Now" },

      // Days of the week
      { word: "星期一", pinyin: "Xīngqī yī", image: "NONE", english: "Monday" },
      { word: "星期二", pinyin: "Xīngqī èr", image: "NONE", english: "Tuesday" },
      { word: "星期三", pinyin: "Xīngqī sān", image: "NONE", english: "Wednesday" },
      { word: "星期四", pinyin: "Xīngqī sì", image: "NONE", english: "Thursday" },
      { word: "星期五", pinyin: "Xīngqī wǔ", image: "NONE", english: "Friday" },
      { word: "星期六", pinyin: "Xīngqī liù", image: "NONE", english: "Saturday" },
      { word: "星期天", pinyin: "Xīngqī tiān", image: "NONE", english: "Sunday" },

      // Months
      { word: "一月", pinyin: "Yīyuè", imageURL: "img/January.png", english: "January" },
      { word: "二月", pinyin: "Èryuè", imageURL: "img/February.png", english: "February" },
      { word: "三月", pinyin: "Sānyuè", imageURL: "img/March.png", english: "March" },
      { word: "四月", pinyin: "Sìyuè", imageURL: "img/April.png", english: "April" },
      { word: "五月", pinyin: "Wǔyuè", imageURL: "img/May.png", english: "May" },
      { word: "六月", pinyin: "Liùyuè", imageURL: "img/June.png", english: "June" },
      { word: "七月", pinyin: "Qīyuè", imageURL: "img/July.png", english: "July" },
      { word: "八月", pinyin: "Bāyuè", imageURL: "img/August.png", english: "August" },
      { word: "九月", pinyin: "Jiǔyuè", imageURL: "img/September.png", english: "September" },
      { word: "十月", pinyin: "Shíyuè", imageURL: "img/October.png", english: "October" },
      { word: "十一月", pinyin: "Shíyīyuè", imageURL: "img/November.png", english: "November" },
      { word: "十二月", pinyin: "Shí'èryuè", imageURL: "img/December.png", english: "December" },
    ],
  },
  animals: {
    label: "Animals",
    pinyinLabel: "Dòngwù",
    chinese: "动物",
    words: [
      { word: "狗", pinyin: "Gǒu", image: "🐶", english: "Dog" },
      { word: "猫", pinyin: "Māo", image: "🐱", english: "Cat" },
      { word: "鸟", pinyin: "Niǎo", image: "🐦", english: "Bird" },
      { word: "马", pinyin: "Mǎ", image: "🐴", english: "Horse" },
      { word: "羊", pinyin: "Yáng", image: "🐑", english: "Sheep" },
      { word: "猪", pinyin: "Zhū", image: "🐷", english: "Pig" },
      { word: "兔子", pinyin: "Tùzi", image: "🐇", english: "Rabbit" },
      { word: "熊猫", pinyin: "Xióngmāo", image: "🐼", english: "Panda" },
      { word: "老虎", pinyin: "Lǎohǔ", image: "🐯", english: "Tiger" },
      { word: "鱼", pinyin: "Yú", image: "🐟", english: "Fish" },
      { word: "仓鼠", pinyin: "Cāngshǔ", image: "🐹", english: "Hamster" },
      { word: "猴子", pinyin: "Hóuzi", image: "🐒", english: "Monkey" },
    ]
  },
  colors: {
    label: "Colors",
    pinyinLabel: "Yánsè",
    chinese: "颜色",
    words: [
      { word: "红色", pinyin: "Hóngsè", image: "🟥", english: "Red" },
      { word: "蓝色", pinyin: "Lánsè", image: "🟦", english: "Blue" },
      { word: "绿色", pinyin: "Lǜsè", image: "🟩", english: "Green" },
      { word: "黄色", pinyin: "Huángsè", image: "🟨", english: "Yellow" },
      { word: "黑色", pinyin: "Hēisè", image: "⬛", english: "Black" },
      { word: "白色", pinyin: "Báisè", imageURL: "img/white.png", english: "White" },
      { word: "橙色", pinyin: "Chéngsè", image: "🟧", english: "Orange" },
      { word: "紫色", pinyin: "Zǐsè", image: "🟪", english: "Purple" },
      { word: "粉色", pinyin: "Fěnsè", imageURL: "img/pink.png", english: "Pink" },
      { word: "灰色", pinyin: "Huīsè", image: "⬜", english: "Gray" },
    ]
  },
  shapes: {
    label: "Shapes",
      pinyinLabel: "Xíngzhuàng",
      chinese: "形状",
      words: [
        { word: "圆形", pinyin: "Yuánxíng", image: "🔵", english: "Circle" },
        { word: "方形", pinyin: "Fāngxíng", image: "◼️", english: "Square" },
        { word: "三角形", pinyin: "Sānjiǎoxíng", image: "🔺", english: "Triangle" },
        { word: "菱形", pinyin: "Língxíng", image: "♦️", english: "Diamond" },
        { word: "心形", pinyin: "Xīnxíng", image: "❤️", english: "Heart" },
        { word: "长方形", pinyin: "Chángfāngxíng", imageURL: "img/rectangle.png", english: "Rectangle" },
      ]
  },
  adjectives: {
    label: "Adjectives",
    pinyinLabel: "Xíngróngcí",
    chinese: "形容词",
    words: [
      { word: "好", pinyin: "Hǎo", image: "👍", english: "Good" },
      { word: "坏", pinyin: "Huài", image: "👎", english: "Bad" },
      { word: "大", pinyin: "Dà", imageURL: "img/big.jpg", english: "Big" },
      { word: "小", pinyin: "Xiǎo", imageURL: "img/small.jpg", english: "Small" },
      { word: "干净", pinyin: "Gānjìng", imageURL: "img/clean.png", english: "Clean" },
      { word: "脏", pinyin: "Zāng", imageURL: "img/dirty.png", english: "Dirty" },
      { word: "凶", pinyin: "Xiōng", imageURL: "img/mean.png", english: "Mean" },
      { word: "多", pinyin: "Duō", imageURL: "img/many.png", english: "Many" },
      { word: "少", pinyin: "Shǎo", imageURL: "img/few.png", english: "Few" },
      { word: "漂亮", pinyin: "Piàoliàng", imageURL: "img/beautiful.png", english: "Beautiful" },
      { word: "高", pinyin: "Gāo", imageURL: "img/tall.png", english: "Tall, High" },
      { word: "低", pinyin: "Dī", imageURL: "img/low.png", english: "Low" },
      { word: "热", pinyin: "Rè", imageURL: "img/hot.png", english: "Hot" },
      { word: "冷", pinyin: "Lěng", imageURL: "img/cold.png", english: "Cold" },
      { word: "生病", pinyin: "Shēngbìng", image: "🤒", english: "Sick" },
      { word: "健康", pinyin: "Jiànkāng", imageURL: "img/healthy.png", english: "Healthy" },
      { word: "好笑", pinyin: "Hǎoxiào", image: "NONE", english: "Funny" },
      { word: "聪明", pinyin: "Cōngmíng", imageURL: "img/smart.png", english: "Smart" },
      { word: "笨", pinyin: "Bèn", imageURL: "img/dumb.png", english: "Dumb" },
      { word: "黏", pinyin: "Nián", imageURL: "img/sticky.png", english: "Sticky" },
      { word: "圆", pinyin: "Yuán", image: "⭕", english: "Round" },
    ]
  },
  locationDirection: {
    label: "Direction",
    pinyinLabel: "Fāngxiàng",
    chinese: "方向",
    words: [
      { word: "左", pinyin: "Zuǒ", image: "⬅️", english: "Left" },
      { word: "右", pinyin: "Yòu", image: "➡️", english: "Right" },
      { word: "上", pinyin: "Shàng", image: "⬆️", english: "Up" },
      { word: "下", pinyin: "Xià", image: "⬇️", english: "Down" },
      { word: "里", pinyin: "Lǐ", imageURL: "img/in.png", english: "In" },
      { word: "外", pinyin: "Wài", imageURL: "img/out.png", english: "Out" },
      { word: "上面", pinyin: "Shàngmiàn", imageURL: "img/above.png", english: "Above" },
      { word: "下面", pinyin: "Xiàmiàn", imageURL: "img/below.png", english: "Below" },
      { word: "后面", pinyin: "Hòumiàn", imageURL: "img/behind.png", english: "Behind" },
      { word: "前面", pinyin: "Qiánmiàn", imageURL: "img/infront.png", english: "In front of" },
      { word: "旁边", pinyin: "Pángbiān", imageURL: "img/nextto.png", english: "Next to" },
      { word: "离很远", pinyin: "Lí hěn yuǎn", imageURL: "img/far.png", english: "Far from" },
      { word: "近", pinyin: "Jìn", imageURL: "img/near.png", english: "Near" },
    ],
  },
  people: {
    label: "People",
    pinyinLabel: "Rén",
    chinese: "人",
    words: [
      { word: "朋友", pinyin: "Péngyǒu", image: "👫", english: "Friend" },
      { word: "老师", pinyin: "Lǎoshī", image: "👩‍🏫", english: "Teacher" },
      { word: "学生", pinyin: "Xuéshēng", image: "👩‍🎓", english: "Student" },
      { word: "女人", pinyin: "Nǚrén", image: "👩", english: "Woman" },
      { word: "女士", pinyin: "Nǚshì", image: "💁‍♀️", english: "Lady" },
      { word: "人", pinyin: "Rén", image: "👤", english: "Person" },
      { word: "孩子", pinyin: "Háizi", image: "🧒", english: "Child/Kid" },
      { word: "儿子", pinyin: "Érzi", imageURL: "img/son.png", english: "Son" },
      { word: "女儿", pinyin: "Nǚ’ér", imageURL: "img/daughter.png", english: "Daughter" },
      { word: "医生", pinyin: "Yīshēng", image: "👨‍⚕️", english: "Doctor" },
      { word: "名字", pinyin: "Míngzi", imageURL: "img/name.png", english: "Name" },
    ]
  },
  places: {
    label: "Places",
    pinyinLabel: "Dìfāng",
    chinese: "地方",
    words: [
      { word: "家", pinyin: "Jiā", image: "🏠", english: "Home, Family" },
      { word: "火车站", pinyin: "Huǒchēzhàn", image: "🚉", english: "Train Station" },
      { word: "医院", pinyin: "Yīyuàn", image: "🏥", english: "Hospital" },
      { word: "学校", pinyin: "Xuéxiào", imageURL: "img/school.png", english: "School" },
      { word: "公园", pinyin: "Gōngyuán", imageURL: "img/playground.png", english: "Park/Playground" },
      { word: "商店", pinyin: "Shāngdiàn", imageURL: "img/store.png", english: "Store" },
      { word: "图书馆", pinyin: "Túshūguǎn", imageURL: "img/library.png", english: "Library" },
      { word: "饭店", pinyin: "Fàndiàn", imageURL: "img/restaurant.png", english: "Restaurant" },
      { word: "机场", pinyin: "Jīchǎng", imageURL: "img/airport.png", english: "Airport" },
      { word: "飞机", pinyin: "Fēijī", image: "✈️", english: "Airplane" },
      { word: "车", pinyin: "Chē", image: "🚗", english: "Car" },
      { word: "超市", pinyin: "Chāoshì", imageURL: "img/supermarket.png", english: "Supermarket" },
      { word: "电影院", pinyin: "Diànyǐngyuàn", imageURL: "img/cinema.png", english: "Cinema" },
    ]
  },
  park: {
    label: "Park",
    pinyinLabel: "Gōngyuán",
    chinese: "公园",
    words: [
      { word: "树", pinyin: "Shù", image: "🌳", english: "Tree" },
      { word: "滑梯", pinyin: "Huátī", image: "🛝", english: "Slide" },
      { word: "花", pinyin: "Huā", image: "🌸", english: "Flower" },
      { word: "喷泉", pinyin: "Pēnquán", image: "⛲", english: "Fountain" },
      { word: "木屑", pinyin: "Mùxiè", imageURL: "img/mulch.jpg", english: "Wood chips/Mulch" },
      { word: "秋千", pinyin: "Qiūqiān", imageURL: "img/swing.png", english: "Swing" },
      { word: "沙坑", pinyin: "Shākēng", imageURL: "img/sandbox.png", english: "Sandbox" },
      { word: "草地", pinyin: "Cǎodì", imageURL: "img/grass.png", english: "Grass" },
      { word: "长椅", pinyin: "Chángyǐ", imageURL: "img/bench.png", english: "Bench" },
      { word: "棍子", pinyin: "Gùnzi", imageURL: "img/stick.png", english: "Stick" },
      { word: "小路", pinyin: "Xiǎolù", imageURL: "img/pathway.png", english: "Pathway" },
      { word: "球场", pinyin: "Qiúchǎng", imageURL: "img/ballcourt.png", english: "Ball court" },
      { word: "球", pinyin: "Qiú", image: "🏀", english: "Ball" },
      { word: "桥", pinyin: "Qiáo", imageURL: "img/bridge.png", english: "Bridge" },
      { word: "小溪", pinyin: "Xiǎoxī", imageURL: "img/creek.png", english: "Creek" },
    ]
  },
  clothing: {
    label: "Clothing",
    pinyinLabel: "Fúzhuāng",
    chinese: "服装",
    words: [
      { word: "裤子", pinyin: "Kùzi", image: "👖", english: "Pants" },
      { word: "裙子", pinyin: "Qúnzi", image: "👗", english: "Dress" },
      { word: "鞋子", pinyin: "Xiézi", image: "👟", english: "Shoes" },
      { word: "帽子", pinyin: "Màozi", image: "🧢", english: "Hat" },
      { word: "衬衫", pinyin: "Chènshān", image: "👕", english: "Shirt" },
      { word: "手套", pinyin: "Shǒutào", image: "🧤", english: "Gloves" },
      { word: "袜子", pinyin: "Wàzi", image: "🧦", english: "Socks" },
      { word: "外套", pinyin: "Wàitào", image: "🧥", english: "Jacket" },
      { word: "围巾", pinyin: "Wéijīn", image: "🧣", english: "Scarf" },
      { word: "背包", pinyin: "Bēibāo", image: "🎒", english: "Backpack" },
    ]
  },
  actions: {
    label: "Actions",
    pinyinLabel: "Xíngwéi",
    chinese: "行为",
    words: [
      { word: "吃", pinyin: "Chī", imageURL: "img/eat.png", english: "Eat" },
      { word: "喝", pinyin: "Hē", imageURL: "img/drink.png", english: "Drink" },
      { word: "走", pinyin: "Zǒu", image: "🚶", english: "Walk" },
      { word: "跑", pinyin: "Pǎo", image: "🏃", english: "Run" },
      { word: "看", pinyin: "Kàn", imageURL: "img/look.png", english: "Look, See" },
      { word: "听", pinyin: "Tīng", imageURL: "img/listen.png", english: "Listen" },
      { word: "说", pinyin: "Shuō", image: "🗣️", english: "Speak" },
      { word: "告诉", pinyin: "Gàosu", imageURL: "img/tell.png", english: "Tell" },
      { word: "写", pinyin: "Xiě", image: "✍️", english: "Write" },
      { word: "玩", pinyin: "Wán", imageURL: "img/play.png", english: "Play" },
      { word: "睡觉", pinyin: "Shuìjiào", image: "🛌", english: "Sleep" },
      { word: "跳", pinyin: "Tiào", imageURL: "img/jump.png", english: "Jump" },
      { word: "游泳", pinyin: "Yóuyǒng", image: "🏊", english: "Swim" },
      { word: "洗澡", pinyin: "Xǐzǎo", imageURL: "img/bathe.png", english: "Bathe" },
			{ word: "刷牙", pinyin: "Shuāyá", imageURL: "img/brushteeth.png", english: "Brush teeth" },
      { word: "洗手", pinyin: "Xǐshǒu", imageURL: "img/washhands.png", english: "Wash hands" },
      { word: "看书", pinyin: "Kànshū", imageURL: "img/read.png", english: "Read" },
      { word: "唱歌", pinyin: "Chànggē", imageURL: "img/sing.png", english: "Sing" },
      { word: "跳舞", pinyin: "Tiàowǔ", image: "💃", english: "Dance" },
      { word: "亲", pinyin: "Qīn", image: "💋", english: "Kiss" },
      { word: "是", pinyin: "Shì", imageURL: "img/be.png", english: "To be" },
      { word: "有", pinyin: "Yǒu", imageURL: "img/have.png", english: "To have" },
      { word: "做", pinyin: "Zuò", imageURL: "img/do.png", english: "To do/cook/make" },
      { word: "学", pinyin: "Xué", imageURL: "img/learn.png", english: "To learn" },
      { word: "叫", pinyin: "Jiào", imageURL: "img/call.png", english: "To be called" },
      { word: "来", pinyin: "Lái", imageURL: "img/come.png", english: "To come" },
      { word: "去", pinyin: "Qù", imageURL: "img/go.png", english: "To go" },
      { word: "想", pinyin: "Xiǎng", image: "🤔", english: "To think, want" },
      { word: "住", pinyin: "Zhù", imageURL: "img/live.png", english: "To live" },
      { word: "抓", pinyin: "Zhuā", imageURL: "img/grab.png", english: "Grab" },
      { word: "带来", pinyin: "Dàilái", imageURL: "img/bring.png", english: "Bring" },
      { word: "扔", pinyin: "Rēng", imageURL: "img/throw.png", english: "Throw" },
      { word: "用", pinyin: "Yòng", imageURL: "img/use.png", english: "Use" },
      { word: "买", pinyin: "Mǎi", imageURL: "img/buy.png", english: "Buy" },
      { word: "戳", pinyin: "Chuō", imageURL: "img/poke.png", english: "Poke" },
      { word: "拉", pinyin: "Lā", imageURL: "img/pull.png", english: "Pull" },
      { word: "坐", pinyin: "Zuò", imageURL: "img/sit.png", english: "To sit" },
      { word: "打开", pinyin: "Dǎkāi", imageURL: "img/open.png", english: "To open" },
    ]
  },
  nature: {
    label: "Nature",
    pinyinLabel: "Zìrán",
    chinese: "自然",
    words: [
      { word: "太阳", pinyin: "Tàiyáng", image: "☀️", english: "Sun" },
      { word: "月亮", pinyin: "Yuèliàng", image: "🌙", english: "Moon" },
      { word: "星星", pinyin: "Xīngxīng", image: "⭐", english: "Star" },
      { word: "雨", pinyin: "Yǔ", image: "🌧️", english: "Rain" },
      { word: "雪", pinyin: "Xuě", image: "❄️", english: "Snow" },
      { word: "风", pinyin: "Fēng", image: "💨", english: "Wind" },
      { word: "山", pinyin: "Shān", image: "⛰️", english: "Mountain" },
      { word: "海", pinyin: "Hǎi", image: "🌊", english: "Sea" },
      { word: "河", pinyin: "Hé", imageURL: "img/river.png", english: "River" },
      { word: "树", pinyin: "Shù", image: "🌳", english: "Tree" },
      { word: "天气", pinyin: "Tiānqì", imageURL: "img/weather.png", english: "Weather" },
    ]
  },
  body: {
    label: "Body",
    pinyinLabel: "Shēntǐ",
    chinese: "身体",
    words: [
      { word: "头", pinyin: "Tóu", image: "🧑", english: "Head" },
      { word: "眼睛", pinyin: "Yǎnjīng", image: "👀", english: "Eyes" },
      { word: "耳朵", pinyin: "Ěrduǒ", image: "👂", english: "Ears" },
      { word: "鼻子", pinyin: "Bízi", image: "👃", english: "Nose" },
      { word: "嘴巴", pinyin: "Zuǐba", image: "👄", english: "Mouth" },
      { word: "手", pinyin: "Shǒu", image: "✋", english: "Hand" },
      { word: "脚", pinyin: "Jiǎo", image: "🦶", english: "Foot" },
      { word: "头发", pinyin: "Tóufǎ", image: "💇", english: "Hair" },
      { word: "腿", pinyin: "Tuǐ", image: "🦵", english: "Leg" },
      { word: "牙齿", pinyin: "Yáchǐ", image: "🦷", english: "Teeth" },
    ]
  },
  commonPhrases: {
    label: "Common Phrases",
    pinyinLabel: "Chángyòng Jùzi",
    chinese: "常用句子",
    image: "💬",
    words: [
      { word: "你好", pinyin: "Nǐ hǎo", image: "👋", english: "Hello" },
      { word: "再见", pinyin: "Zàijiàn", image: "👋", english: "Goodbye" },
      { word: "我不知道", pinyin: "Wǒ bù zhīdào", image: "🤷", english: "I don’t know" },
      { word: "对不起", pinyin: "Duìbuqǐ", image: "😔", english: "Sorry" },
      { word: "请", pinyin: "Qǐng", imageURL: "img/please.png", english: "Please" },
      { word: "谢谢", pinyin: "Xièxie", image: "🙏", english: "Thank you" },
      { word: "没关系", pinyin: "Méi guānxi", image: "👌", english: "It's okay" },
      { word: "好的", pinyin: "Hǎo de", image: "👍", english: "Okay" },
      { word: "不要", pinyin: "Bù yào", image: "✋", english: "Don't" },
      { word: "帮忙", pinyin: "Bāngmáng", imageURL: "img/help.png", english: "Help" },
      { word: "我明白了", pinyin: "Wǒ míngbái le", imageURL: "img/understand.png", english: "I understand" },
      { word: "我不明白", pinyin: "Wǒ bù míngbái", imageURL: "img/idontunderstand.png", english: "I don't understand" },
      { word: "慢一点", pinyin: "Màn yīdiǎn", image: "NONE", english: "Slower" },
      { word: "太快了", pinyin: "Tài kuài le", image: "NONE", english: "Too fast" },
      { word: "多少钱", pinyin: "Duōshǎo qián", imageURL: "img/howmuch.png", english: "How much (cost)?" },
      { word: "早上好", pinyin: "Zǎoshang hǎo", image: "NONE", english: "Good morning" },
      { word: "晚安", pinyin: "Wǎn'ān", image: "NONE", english: "Good night" },
      { word: "我爱你", pinyin: "Wǒ ài nǐ", imageURL: "img/iloveyou.png", english: "I love you" },
      { word: "你在看什么？", pinyin: "Nǐ zài kàn shénme?", imageURL: "img/whatareyouwatching.png", english: "What are you watching?" },
      { word: "哪个", pinyin: "Nǎge", imageURL: "img/which.png", english: "Which" },
      { word: "谁", pinyin: "Shéi", imageURL: "img/who.png", english: "Who" },
      { word: "这是什么？", pinyin: "Zhè shì shénme?", imageURL: "img/whatisthat.png", english: "What’s that?" },
      { word: "双手", pinyin: "Shuāngshǒu", image: "👐", english: "Both hands" },
      { word: "更多", pinyin: "Gèng duō", imageURL: "img/more.png", english: "More" },
      { word: "我想要更多", pinyin: "Wǒ xiǎng yào gèng duō", imageURL: "img/iwantmore.png", english: "I want more" },
      { word: "我想要少一点", pinyin: "Wǒ xiǎng yào shǎo yīdiǎn", image: "NONE", english: "I want less" },
      { word: "你想要什么？", pinyin: "Nǐ xiǎng yào shénme?", imageURL: "img/whatdoyouwant.png", english: "What do you want?" },
      { word: "好了", pinyin: "Hǎole", image: "NONE", english: "All done" },
      { word: "我需要", pinyin: "Wǒ xūyào", image: "NONE", english: "I need" },
      { word: "饭在书包里", pinyin: "Fàn zài shūbāo lǐ", image: "NONE", english: "The food is in the backpack" },
      { word: "这只狗", pinyin: "Zhè zhī gǒu", imageURL: "img/thisdog.png", english: "This dog" },
      { word: "我们不知道狗好不好", pinyin: "Wǒmen bù zhīdào gǒu hǎo bù hǎo", image: "NONE", english: "We don't know if the dog is good" },
      { word: "可以摸狗", pinyin: "Kěyǐ mō gǒu", image: "NONE", english: "You can pet the dog" },
      { word: "我可以做到", pinyin: "Wǒ kěyǐ zuòdào", image: "NONE", english: "I can do it" },
      { word: "可以吃", pinyin: "Kěyǐ chī", image: "NONE", english: "You can eat" },
      { word: "一点点", pinyin: "Yīdiǎn diǎn", image: "NONE", english: "A little bit" },
      { word: "很多", pinyin: "Hěn duō", image: "NONE", english: "A lot" },
      { word: "全部", pinyin: "Quánbù", image: "NONE", english: "All" },
      { word: "我做的", pinyin: "Wǒ zuò de", image: "NONE", english: "I made this" },
      { word: "这个蛋糕是我做的", pinyin: "Zhège dàngāo shì wǒ zuò de", image: "NONE", english: "I made this cake" },
      { word: "这是你做的吗？", pinyin: "Zhè shì nǐ zuò de ma?", image: "NONE", english: "Did you make that?" },
      { word: "你几岁？", pinyin: "Nǐ jǐ suì?", imageURL: "img/howoldareyou.png", english: "How old are you?" },
      { word: "我三岁", pinyin: "Wǒ sān suì", image: "NONE", english: "I am three years old" },
      { word: "电影", pinyin: "Diànyǐng", imageURL: "img/movie.png", english: "Movie" },
      { word: "东西", pinyin: "Dōngxi", imageURL: "img/thing.png", english: "Thing" },
      { word: "词", pinyin: "Cí", imageURL: "img/word.png", english: "Word" },
      { word: "笑话", pinyin: "Xiàohuà", imageURL: "img/joke.png", english: "Joke" },
      { word: "我开玩笑的", pinyin: "Wǒ kāiwánxiào de", image: "NONE", english: "I'm kidding" },
      { word: "擤鼻涕", pinyin: "Xǐng bítì", imageURL: "img/blowyournose.png", english: "Blow your nose" },
      { word: "扔掉", pinyin: "Rēngdiào", image: "🚮", english: "Throw away" },
      { word: "扔掉垃圾", pinyin: "Rēngdiào lājī", imageURL: "img/throwaway.png", english: "Throw away the trash" },
      { word: "关门", pinyin: "Guān mén", imageURL: "img/closethedoor.png", english: "Close the door" },
      { word: "打开窗户", pinyin: "Dǎkāi chuānghu", imageURL: "img/openthewindow.png", english: "Open the window" },
      { word: "给我书", pinyin: "Gěi wǒ shū", imageURL: "img/givebook.png", english: "Give me the book" },
      { word: "把杯子放到桌子上", pinyin: "Bǎ bēizi fàng dào zhuōzi shàng", imageURL: "img/putcupontable.png", english: "Put the cup onto the table" },
      { word: "带来你的书包", pinyin: "Dàilái nǐ de shūbāo", imageURL: "img/bringbackpack.png", english: "Bring your backpack" },
      { word: "怎么说 _？", pinyin: "Zěnme shuō _?", image: "NONE", english: "How do you say _?" },
      { word: "我有问题", pinyin: "Wǒ yǒu wèntí", imageURL: "img/question.png", english: "I have a question" },
      { word: "现在几点？", pinyin: "Xiànzài jǐ diǎn?", imageURL: "img/whattimeisit.png", english: "What time is it?" },
      { word: "现在三点", pinyin: "Xiànzài sān diǎn", imageURL: "img/threeoclock.png", english: "It's 3 o'clock" },
    ]
  },
  pronouns: {
    label: "Pronouns",
    pinyinLabel: "Dàicí",
    chinese: "代词",
    words: [
      { word: "我", pinyin: "Wǒ", image: "🙋‍♂️", english: "I, Me" },
      { word: "你", pinyin: "Nǐ", image: "🙋‍♀️", english: "You" },
      { word: "他,她,它", pinyin: "Tā", image: "👨", english: "He, Him, She, Her, It" },
      { word: "我们", pinyin: "Wǒmen", image: "👥", english: "We, Us" },
      { word: "你们", pinyin: "Nǐmen", image: "👥", english: "You (plural)" },
      { word: "他们", pinyin: "Tāmen", image: "👫", english: "They, Them" }
    ]
  },
};
