const data = {
  food: {
    label: "Food",
    pinyinLabel: "Shíwù",
    chinese: "食物",
    words: [
      { word: "苹果", pinyin: "Píngguǒ", image: "🍎", english: "Apple" },
      { word: "面条", pinyin: "Miàntiáo", imageURL: "img/noodles.png", english: "Noodles" },
      { word: "番茄", pinyin: "Fānqié", image: "🍅", english: "Tomato" },
      { word: "香蕉", pinyin: "Xiāngjiāo", image: "🍌", english: "Banana" },
      { word: "米饭", pinyin: "Mǐfàn", image: "🍚", english: "Rice" },
      { word: "面包", pinyin: "Miànbāo", image: "🍞", english: "Bread" },
      { word: "鸡蛋", pinyin: "Jīdàn", image: "🥚", english: "Egg" },
      { word: "牛奶", pinyin: "Niúnǎi", image: "🥛", english: "Milk" },
      { word: "咖啡", pinyin: "Kāfēi", image: "☕", english: "Coffee" },
      { word: "水", pinyin: "Shuǐ", imageURL: "img/water.png", english: "Water" },
      { word: "茶", pinyin: "Chá", image: "🍵", english: "Tea" },
      { word: "鱼", pinyin: "Yú", image: "🐟", english: "Fish" },
      { word: "鸡肉", pinyin: "Jīròu", image: "🍗", english: "Chicken" },
      { word: "冰淇淋", pinyin: "Bīngqílín", image: "🍦", english: "Ice Cream" },
      { word: "棒冰", pinyin: "Bàngbīng", imageURL: "img/popsicle.png", english: "Popsicle" },
      { word: "草莓", pinyin: "Cǎoméi", image: "🍓", english: "Strawberry" },
      { word: "桔子", pinyin: "Júzi", image: "🍊", english: "Orange" },
      { word: "樱桃", pinyin: "Yīngtáo", image: "🍒", english: "Cherry" },
      { word: "西兰花", pinyin: "Xīlánhuā", image: "🥦", english: "Broccoli" },
      { word: "白菜", pinyin: "Báicài", image: "NONE", english: "Bok Choy" },
      { word: "胡萝卜", pinyin: "Húluóbo", image: "🥕", english: "Carrot" },
      { word: "玉米", pinyin: "Yùmǐ", image: "🌽", english: "Corn" },
      { word: "芹菜", pinyin: "Qíncài", imageURL: "img/celery.png", english: "Celery" },
      { word: "蘑菇", pinyin: "Mógū", image: "🍄‍🟫", english: "Mushroom" },
      { word: "黄瓜", pinyin: "Huángguā", image: "🥒", english: "Cucumber" },
      { word: "蛋糕", pinyin: "Dàngāo", image: "🍰", english: "Cake" },
      { word: "披萨", pinyin: "Pīsà", image: "🍕", english: "Pizza" },
      { word: "意大利面", pinyin: "Yìdàlì miàn", image: "🍝", english: "Spaghetti" },
      { word: "四季豆", pinyin: "Sìjìdòu", image: "NONE", english: "Green bean" },
    ]
  },
  utensils: {
    label: "Utensils",
    pinyinLabel: "Cānjù",
    chinese: "餐具",
    words: [
      { word: "叉子", pinyin: "Chāzi", imageURL: "img/fork.png", english: "Fork" },
      { word: "刀", pinyin: "Dāo", imageURL: "img/knife.png", english: "Knife" },
      { word: "勺子", pinyin: "Sháozi", image: "🥄", english: "Spoon" },
      { word: "筷子", pinyin: "Kuàizi", image: "🥢", english: "Chopsticks" },
      { word: "碗", pinyin: "Wǎn", imageURL: "img/bowl.png", english: "Bowl" },
      { word: "盘子", pinyin: "Pánzi", imageURL: "img/plate.png", english: "Plate" },
      { word: "餐巾", pinyin: "Cānjīn", imageURL: "img/napkin.png", english: "Napkin" },
      { word: "纸巾", pinyin: "Zhǐjīn", imageURL: "img/tissue.png", english: "Tissue" },
    ]
  },
  household: {
    label: "Household",
    pinyinLabel: "Jiāshì",
    chinese: "家事",
    words: [
      { word: "桌子", pinyin: "Zhuōzi", imageURL: "img/table.png", english: "Table" },
      { word: "椅子", pinyin: "Yǐzi", image: "🪑", english: "Chair" },
      { word: "灯", pinyin: "Dēng", image: "💡", english: "Light" },
      { word: "床", pinyin: "Chuáng", image: "🛏️", english: "Bed" },
      { word: "窗户", pinyin: "Chuānghù", image: "🪟", english: "Window" },
      { word: "门", pinyin: "Mén", image: "🚪", english: "Door" },
      { word: "钥匙", pinyin: "Yàoshi", image: "🔑", english: "Keys" },
      { word: "冰箱", pinyin: "Bīngxiāng", imageURL: "img/fridge.png", english: "Fridge" },
      { word: "沙发", pinyin: "Shāfā", image: "🛋️", english: "Sofa" },
      { word: "书", pinyin: "Shū", imageURL: "img/book.png", english: "Book" },
      { word: "眼镜", pinyin: "Yǎnjìng", image: "👓", english: "Glasses" },
      { word: "电脑", pinyin: "Diànnǎo", image: "💻", english: "Computer" },
      { word: "耳机", pinyin: "Ěrjī", image: "🎧", english: "Headphones" },
      { word: "耳塞", pinyin: "Ěrsāi", imageURL: "img/earprotection.png", english: "Ear Protection" },
      { word: "厨房", pinyin: "Chúfáng", imageURL: "img/kitchen.png", english: "Kitchen" },
      { word: "锅", pinyin: "Guō", imageURL: "img/pot.png", english: "Pot" },
      { word: "平底锅", pinyin: "Píngdǐguō", imageURL: "img/pan.png", english: "Pan" },
      { word: "炉子", pinyin: "Lúzi", imageURL: "img/stove.png", english: "Stove" },
      { word: "烤箱", pinyin: "Kǎoxiāng", imageURL: "img/oven.png", english: "Oven" },
      { word: "吸尘器", pinyin: "Xīchénqì", imageURL: "img/vacuum.png", english: "Vacuum" },
      { word: "钱", pinyin: "Qián", image: "💵", english: "Money" },
      { word: "电视", pinyin: "Diànshì", image: "📺", english: "TV" },
      { word: "电视节目", pinyin: "Diànshì Jiémù", imageURL: "img/tvshow.png", english: "TV Show" },
      { word: "歌", pinyin: "Gē", image: "🎵", english: "Song" },
    ]
  },
	routines: {
		label: "Routines",
		pinyinLabel: "Rìcháng",
		chinese: "日常",
		words: [
			{ word: "刷牙", pinyin: "Shuāyá", imageURL: "img/brushteeth.png", english: "Brush teeth" },
			{ word: "吃早餐", pinyin: "Chī zǎocān", imageURL: "img/eatbreakfast.png", english: "Eat breakfast" },
			{ word: "吃午饭", pinyin: "Chī wǔfàn", imageURL: "img/eatlunch.png", english: "Eat lunch" },
			{ word: "吃晚饭", pinyin: "Chī wǎnfàn", imageURL: "img/eatdinner.png", english: "Eat dinner" },
			{ word: "起床", pinyin: "Qǐchuáng", image: "NONE", english: "Wake up" },
			{ word: "上班", pinyin: "Shàngbān", image: "NONE", english: "Go to work" },
			{ word: "下班", pinyin: "Xiàbān", image: "NONE", english: "Finish work" },
			{ word: "午睡时间", pinyin: "Wǔshuì shíjiān", image: "NONE", english: "Nap time" },
			{ word: "睡觉时间", pinyin: "Shuìjiào shíjiān", image: "NONE", english: "Bedtime" },
      { word: "牙线", pinyin: "Yáxiàn", image: "NONE", english: "Floss" },
      { word: "漱口", pinyin: "Shùkǒu", image: "NONE", english: "Swish" },
      { word: "药", pinyin: "Yào", image: "💊", english: "Medicine" },
      { word: "乳液", pinyin: "Rǔyè", image: "🧴", english: "Lotion" },
      { word: "洗衣服", pinyin: "Xǐ yīfu", imageURL: "img/laundry.png", english: "Laundry" },
      { word: "脏衣服", pinyin: "Zāng yīfu", imageURL: "img/dirtylaundry.png", english: "Dirty laundry" },
		]
	},
  emotions: {
    label: "Emotions",
    pinyinLabel: "Qínggǎn",
    chinese: "情感",
    words: [
      { word: "快乐", pinyin: "Kuàilè", image: "😊", english: "Happy" },
      { word: "伤心", pinyin: "Shāngxīn", image: "😢", english: "Sad" },
      { word: "生气", pinyin: "Shēngqì", image: "😡", english: "Angry" },
      { word: "惊讶", pinyin: "Jīngyà", image: "😮", english: "Surprised" },
      { word: "害怕", pinyin: "Hàipà", image: "NONE", english: "Afraid" },
      { word: "兴奋", pinyin: "Xīngfèn", imageURL: "img/excited.png", english: "Excited" },
      { word: "累", pinyin: "Lèi", image: "🥱", english: "Tired" },
      { word: "担心", pinyin: "Dānxīn", image: "NONE", english: "Worried" },
      { word: "放松", pinyin: "Fàngsōng", image: "NONE", english: "Relaxed" },
      { word: "无聊", pinyin: "Wúliáo", image: "NONE", english: "Bored" },
    ]
  },
  numbers: {
    label: "Numbers",
    pinyinLabel: "Shùzì",
    chinese: "数字",
    words: [
      { word: "一", pinyin: "Yī", image: "1️⃣", english: "One" },
      { word: "二", pinyin: "Èr", image: "2️⃣", english: "Two" },
      { word: "三", pinyin: "Sān", image: "3️⃣", english: "Three" },
      { word: "四", pinyin: "Sì", image: "4️⃣", english: "Four" },
      { word: "五", pinyin: "Wǔ", image: "5️⃣", english: "Five" },
      { word: "六", pinyin: "Liù", image: "6️⃣", english: "Six" },
      { word: "七", pinyin: "Qī", image: "7️⃣", english: "Seven" },
      { word: "八", pinyin: "Bā", image: "8️⃣", english: "Eight" },
      { word: "九", pinyin: "Jiǔ", image: "9️⃣", english: "Nine" },
      { word: "十", pinyin: "Shí", image: "🔟", english: "Ten" },
    ]
  },
  time: {
    label: "Time",
    pinyinLabel: "Shíjiān",
    chinese: "时间",
    image: "📆",
    words: [
      { word: "分钟", pinyin: "Fēnzhōng", image: "NONE", english: "Minutes" },
      { word: "小时", pinyin: "Xiǎoshí", image: "NONE", english: "Hours" },
      { word: "天", pinyin: "Tiān", image: "NONE", english: "Day" },
      { word: "星期", pinyin: "Xīngqī", image: "NONE", english: "Week" },
      { word: "月", pinyin: "Yuè", image: "NONE", english: "Month" },

      // Days of the week
      { word: "星期一", pinyin: "Xīngqī yī", image: "NONE", english: "Monday" },
      { word: "星期二", pinyin: "Xīngqī èr", image: "NONE", english: "Tuesday" },
      { word: "星期三", pinyin: "Xīngqī sān", image: "NONE", english: "Wednesday" },
      { word: "星期四", pinyin: "Xīngqī sì", image: "NONE", english: "Thursday" },
      { word: "星期五", pinyin: "Xīngqī wǔ", image: "NONE", english: "Friday" },
      { word: "星期六", pinyin: "Xīngqī liù", image: "NONE", english: "Saturday" },
      { word: "星期天", pinyin: "Xīngqī tiān", image: "NONE", english: "Sunday" },

      // Months
      { word: "一月", pinyin: "Yīyuè", image: "NONE", english: "January" },
      { word: "二月", pinyin: "Èryuè", image: "NONE", english: "February" },
      { word: "三月", pinyin: "Sānyuè", image: "NONE", english: "March" },
      { word: "四月", pinyin: "Sìyuè", image: "NONE", english: "April" },
      { word: "五月", pinyin: "Wǔyuè", image: "NONE", english: "May" },
      { word: "六月", pinyin: "Liùyuè", image: "NONE", english: "June" },
      { word: "七月", pinyin: "Qīyuè", image: "NONE", english: "July" },
      { word: "八月", pinyin: "Bāyuè", image: "NONE", english: "August" },
      { word: "九月", pinyin: "Jiǔyuè", image: "NONE", english: "September" },
      { word: "十月", pinyin: "Shíyuè", image: "NONE", english: "October" },
      { word: "十一月", pinyin: "Shíyīyuè", image: "NONE", english: "November" },
      { word: "十二月", pinyin: "Shí'èryuè", image: "NONE", english: "December" },
    ],
  },
  animals: {
    label: "Animals",
    pinyinLabel: "Dòngwù",
    chinese: "动物",
    words: [
      { word: "狗", pinyin: "Gǒu", image: "🐶", english: "Dog" },
      { word: "猫", pinyin: "Māo", image: "🐱", english: "Cat" },
      { word: "鸟", pinyin: "Niǎo", image: "🐦", english: "Bird" },
      { word: "马", pinyin: "Mǎ", image: "🐴", english: "Horse" },
      { word: "羊", pinyin: "Yáng", image: "🐑", english: "Sheep" },
      { word: "猪", pinyin: "Zhū", image: "🐷", english: "Pig" },
      { word: "兔子", pinyin: "Tùzi", image: "🐇", english: "Rabbit" },
      { word: "熊猫", pinyin: "Xióngmāo", image: "🐼", english: "Panda" },
      { word: "老虎", pinyin: "Lǎohǔ", image: "🐯", english: "Tiger" },
      { word: "鱼", pinyin: "Yú", image: "🐟", english: "Fish" },
      { word: "仓鼠", pinyin: "Cāngshǔ", image: "🐹", english: "Hamster" },
    ]
  },
  colors: {
    label: "Colors",
    pinyinLabel: "Yánsè",
    chinese: "颜色",
    words: [
      { word: "红色", pinyin: "Hóngsè", image: "🟥", english: "Red" },
      { word: "蓝色", pinyin: "Lánsè", image: "🟦", english: "Blue" },
      { word: "绿色", pinyin: "Lǜsè", image: "🟩", english: "Green" },
      { word: "黄色", pinyin: "Huángsè", image: "🟨", english: "Yellow" },
      { word: "黑色", pinyin: "Hēisè", image: "⬛", english: "Black" },
      { word: "白色", pinyin: "Báisè", imageURL: "img/white.png", english: "White" },
      { word: "橙色", pinyin: "Chéngsè", image: "🟧", english: "Orange" },
      { word: "紫色", pinyin: "Zǐsè", image: "🟪", english: "Purple" },
      { word: "粉色", pinyin: "Fěnsè", imageURL: "img/pink.png", english: "Pink" },
      { word: "灰色", pinyin: "Huīsè", image: "⬜", english: "Gray" },
    ]
  },
  adjectives: {
    label: "Adjectives",
    pinyinLabel: "Xíngróngcí",
    chinese: "形容词",
    words: [
      { word: "好", pinyin: "Hǎo", image: "👍", english: "Good" },
      { word: "坏", pinyin: "Huài", image: "👎", english: "Bad" },
      { word: "大", pinyin: "Dà", imageURL: "img/big.jpg", english: "Big" },
      { word: "小", pinyin: "Xiǎo", imageURL: "img/small.jpg", english: "Small" },
      { word: "干净", pinyin: "Gānjìng", image: "NONE", english: "Clean" },
      { word: "脏", pinyin: "Zāng", image: "NONE", english: "Dirty" },
      { word: "刻薄", pinyin: "Kèbó", image: "NONE", english: "Mean" },
      { word: "友善", pinyin: "Yǒushàn", image: "NONE", english: "Nice" },
      { word: "多", pinyin: "Duō", image: "NONE", english: "Many" },
      { word: "少", pinyin: "Shǎo", image: "NONE", english: "Few" },
      { word: "漂亮", pinyin: "Piàoliàng", image: "NONE", english: "Beautiful" },
      { word: "高", pinyin: "Gāo", image: "NONE", english: "Tall, High" },
      { word: "低", pinyin: "Dī", image: "NONE", english: "Low" },
      { word: "热", pinyin: "Rè", image: "NONE", english: "Hot" },
      { word: "冷", pinyin: "Lěng", image: "NONE", english: "Cold" },
      { word: "生病", pinyin: "Shēngbìng", image: "🤒", english: "Sick" },
      { word: "健康", pinyin: "Jiànkāng", image: "NONE", english: "Healthy" },
      { word: "聪明", pinyin: "Cōngmíng", image: "NONE", english: "Smart" },
      { word: "笨", pinyin: "Bèn", image: "NONE", english: "Dumb" },
    ]
  },
  locationDirection: {
    label: "Direction",
    pinyinLabel: "Fāngxiàng",
    chinese: "方向",
    words: [
      { word: "左", pinyin: "Zuǒ", image: "⬅️", english: "Left" },
      { word: "右", pinyin: "Yòu", image: "➡️", english: "Right" },
      { word: "上", pinyin: "Shàng", image: "⬆️", english: "Up" },
      { word: "下", pinyin: "Xià", image: "⬇️", english: "Down" },
      { word: "里", pinyin: "Lǐ", image: "NONE", english: "In" },
      { word: "外", pinyin: "Wài", image: "NONE", english: "Out" },
      { word: "上面", pinyin: "Shàngmiàn", image: "NONE", english: "Above" },
      { word: "下面", pinyin: "Xiàmiàn", image: "NONE", english: "Below" },
      { word: "后面", pinyin: "Hòumiàn", image: "NONE", english: "Behind" },
      { word: "前面", pinyin: "Qiánmiàn", image: "NONE", english: "In front of" },
      { word: "旁边", pinyin: "Pángbiān", image: "NONE", english: "Next to" },
      { word: "离很远", pinyin: "Lí hěn yuǎn", image: "NONE", english: "Far from" },
      { word: "近", pinyin: "Jìn", image: "NONE", english: "Near" },
    ],
  },
  people: {
    label: "People",
    pinyinLabel: "Rén",
    chinese: "人",
    words: [
      { word: "朋友", pinyin: "Péngyǒu", image: "👫", english: "Friend" },
      { word: "老师", pinyin: "Lǎoshī", image: "👩‍🏫", english: "Teacher" },
      { word: "学生", pinyin: "Xuéshēng", image: "👩‍🎓", english: "Student" },
      { word: "人", pinyin: "Rén", image: "👤", english: "Person" },
      { word: "名字", pinyin: "Míngzi", image: "NONE", english: "Name" },
    ]
  },
  places: {
    label: "Places",
    pinyinLabel: "Dìfāng",
    chinese: "地方",
    words: [
      { word: "家", pinyin: "Jiā", image: "🏠", english: "Home, Family" },
      { word: "火车站", pinyin: "Huǒchēzhàn", image: "🚉", english: "Train Station" },
      { word: "医院", pinyin: "Yīyuàn", image: "🏥", english: "Hospital" },
      { word: "学校", pinyin: "Xuéxiào", imageURL: "img/school.png", english: "School" },
      { word: "公园", pinyin: "Gōngyuán", image: "NONE", english: "Park" },
      { word: "游乐场", pinyin: "Yóulèchǎng", image: "NONE", english: "Playground" },
      { word: "商店", pinyin: "Shāngdiàn", image: "NONE", english: "Store" },
      { word: "图书馆", pinyin: "Túshūguǎn", image: "NONE", english: "Library" },
      { word: "餐厅", pinyin: "Cāntīng", image: "NONE", english: "Restaurant" },
      { word: "机场", pinyin: "Jīchǎng", image: "NONE", english: "Airport" },
      { word: "超市", pinyin: "Chāoshì", image: "NONE", english: "Supermarket" },
      { word: "电影院", pinyin: "Diànyǐngyuàn", image: "NONE", english: "Cinema" },
    ]
  },
  park: {
    label: "Park",
    pinyinLabel: "Gōngyuán",
    chinese: "公园",
    words: [
      { word: "树", pinyin: "Shù", image: "🌳", english: "Tree" },
      { word: "滑梯", pinyin: "Huátī", image: "🛝", english: "Slide" },
      { word: "花", pinyin: "Huā", image: "🌸", english: "Flower" },
      { word: "喷泉", pinyin: "Pēnquán", image: "⛲", english: "Fountain" },
      { word: "木屑", pinyin: "Mùxiè", image: "NONE", english: "Wood chips/Mulch" },
      { word: "秋千", pinyin: "Qiūqiān", image: "NONE", english: "Swing" },
      { word: "沙坑", pinyin: "Shākēng", image: "NONE", english: "Sandbox" },
      { word: "草地", pinyin: "Cǎodì", image: "NONE", english: "Grass" },
      { word: "长椅", pinyin: "Chángyǐ", imageURL: "img/bench.png", english: "Bench" },
      { word: "棍子", pinyin: "Gùnzi", image: "NONE", english: "Stick" },
      { word: "小路", pinyin: "Xiǎolù", image: "NONE", english: "Pathway" },
      { word: "球场", pinyin: "Qiúchǎng", image: "NONE", english: "Ball court" },
      { word: "游乐设施", pinyin: "Yóulè shèshī", image: "NONE", english: "Play equipment" },
      { word: "桥", pinyin: "Qiáo", image: "NONE", english: "Bridge" },
      { word: "小溪", pinyin: "Xiǎoxī", image: "NONE", english: "Creek" },
    ]
  },
  clothing: {
    label: "Clothing",
    pinyinLabel: "Fúzhuāng",
    chinese: "服装",
    words: [
      { word: "裤子", pinyin: "Kùzi", image: "👖", english: "Pants" },
      { word: "裙子", pinyin: "Qúnzi", image: "👗", english: "Dress" },
      { word: "鞋子", pinyin: "Xiézi", image: "👟", english: "Shoes" },
      { word: "帽子", pinyin: "Màozi", image: "🧢", english: "Hat" },
      { word: "衬衫", pinyin: "Chènshān", image: "👕", english: "Shirt" },
      { word: "手套", pinyin: "Shǒutào", image: "🧤", english: "Gloves" },
      { word: "袜子", pinyin: "Wàzi", image: "🧦", english: "Socks" },
      { word: "外套", pinyin: "Wàitào", image: "🧥", english: "Jacket" },
      { word: "围巾", pinyin: "Wéijīn", image: "🧣", english: "Scarf" },
      { word: "背包", pinyin: "Bēibāo", image: "🎒", english: "Backpack" },
    ]
  },
  actions: {
    label: "Actions",
    pinyinLabel: "Xíngwéi",
    chinese: "行为",
    words: [
      { word: "吃", pinyin: "Chī", imageURL: "img/eat.png", english: "Eat" },
      { word: "喝", pinyin: "Hē", imageURL: "img/drink.png", english: "Drink" },
      { word: "走", pinyin: "Zǒu", image: "🚶", english: "Walk" },
      { word: "跑", pinyin: "Pǎo", image: "🏃", english: "Run" },
      { word: "看", pinyin: "Kàn", imageURL: "img/look.png", english: "Look, See" },
      { word: "听", pinyin: "Tīng", imageURL: "img/listen.png", english: "Listen" },
      { word: "说", pinyin: "Shuō", image: "🗣️", english: "Speak" },
      { word: "写", pinyin: "Xiě", image: "✍️", english: "Write" },
      { word: "玩", pinyin: "Wán", imageURL: "img/play.png", english: "Play" },
      { word: "睡觉", pinyin: "Shuìjiào", image: "🛌", english: "Sleep" },
      { word: "跳", pinyin: "Tiào", image: "NONE", english: "Jump" },
      { word: "游泳", pinyin: "Yóuyǒng", image: "🏊", english: "Swim" },
      { word: "洗澡", pinyin: "Xǐzǎo", image: "NONE", english: "Bathe" },
			{ word: "刷牙", pinyin: "Shuāyá", imageURL: "img/brushteeth.png", english: "Brush teeth" },
      { word: "洗手", pinyin: "Xǐshǒu", imageURL: "img/washhands.png", english: "Wash hands" },
      { word: "看书", pinyin: "Kànshū", image: "NONE", english: "Read" },
      { word: "唱歌", pinyin: "Chànggē", image: "NONE", english: "Sing" },
      { word: "跳舞", pinyin: "Tiàowǔ", image: "💃", english: "Dance" },
      { word: "是", pinyin: "Shì", image: "NONE", english: "To be" },
      { word: "有", pinyin: "Yǒu", image: "NONE", english: "To have" },
      { word: "做", pinyin: "Zuò", image: "NONE", english: "To do" },
      { word: "学", pinyin: "Xué", image: "NONE", english: "To learn" },
      { word: "叫", pinyin: "Jiào", image: "NONE", english: "To be called" },
      { word: "来", pinyin: "Lái", image: "NONE", english: "To come" },
      { word: "去", pinyin: "Qù", image: "NONE", english: "To go" },
      { word: "想", pinyin: "Xiǎng", image: "🤔", english: "To think, want" },
      { word: "住", pinyin: "Zhù", image: "NONE", english: "To live" },
    ]
  },
  nature: {
    label: "Nature",
    pinyinLabel: "Zìrán",
    chinese: "自然",
    words: [
      { word: "太阳", pinyin: "Tàiyáng", image: "☀️", english: "Sun" },
      { word: "月亮", pinyin: "Yuèliàng", image: "🌙", english: "Moon" },
      { word: "星星", pinyin: "Xīngxīng", image: "⭐", english: "Star" },
      { word: "雨", pinyin: "Yǔ", image: "🌧️", english: "Rain" },
      { word: "雪", pinyin: "Xuě", image: "❄️", english: "Snow" },
      { word: "风", pinyin: "Fēng", image: "💨", english: "Wind" },
      { word: "山", pinyin: "Shān", image: "⛰️", english: "Mountain" },
      { word: "海", pinyin: "Hǎi", image: "🌊", english: "Sea" },
      { word: "河", pinyin: "Hé", image: "NONE", english: "River" },
      { word: "树", pinyin: "Shù", image: "🌳", english: "Tree" },
    ]
  },
  body: {
    label: "Body",
    pinyinLabel: "Shēntǐ",
    chinese: "身体",
    words: [
      { word: "头", pinyin: "Tóu", image: "🧑", english: "Head" },
      { word: "眼睛", pinyin: "Yǎnjīng", image: "👀", english: "Eyes" },
      { word: "耳朵", pinyin: "Ěrduǒ", image: "👂", english: "Ears" },
      { word: "鼻子", pinyin: "Bízi", image: "👃", english: "Nose" },
      { word: "嘴巴", pinyin: "Zuǐba", image: "👄", english: "Mouth" },
      { word: "手", pinyin: "Shǒu", image: "✋", english: "Hand" },
      { word: "脚", pinyin: "Jiǎo", image: "🦶", english: "Foot" },
      { word: "头发", pinyin: "Tóufǎ", image: "💇", english: "Hair" },
      { word: "腿", pinyin: "Tuǐ", image: "🦵", english: "Leg" },
      { word: "牙齿", pinyin: "Yáchǐ", image: "🦷", english: "Teeth" },
    ]
  },
  commonPhrases: {
    label: "Common Phrases",
    pinyinLabel: "Chángyòng Jùzi",
    chinese: "常用句子",
    image: "💬",
    words: [
      { word: "你好", pinyin: "Nǐ hǎo", image: "👋", english: "Hello" },
      { word: "再见", pinyin: "Zàijiàn", image: "👋", english: "Goodbye" },
      { word: "我不知道", pinyin: "Wǒ bù zhīdào", image: "🤷", english: "I don’t know" },
      { word: "对不起", pinyin: "Duìbuqǐ", image: "😔", english: "Sorry" },
      { word: "请", pinyin: "Qǐng", image: "NONE", english: "Please" },
      { word: "谢谢", pinyin: "Xièxie", image: "NONE", english: "Thank you" },
      { word: "没关系", pinyin: "Méi guānxi", image: "👌", english: "It's okay" },
      { word: "好的", pinyin: "Hǎo de", image: "👍", english: "Okay" },
      { word: "不要", pinyin: "Bù yào", image: "✋", english: "Don't" },
      { word: "帮忙", pinyin: "Bāngmáng", image: "NONE", english: "Help" },
      { word: "告诉我", pinyin: "Gàosu wǒ", image: "NONE", english: "Tell me" },
      { word: "我明白了", pinyin: "Wǒ míngbái le", image: "NONE", english: "I understand" },
      { word: "我不明白", pinyin: "Wǒ bù míngbái", image: "NONE", english: "I don't understand" },
      { word: "多少钱", pinyin: "Duōshǎo qián", image: "NONE", english: "How much (cost)?" },
      { word: "好的早上", pinyin: "Hǎo de zǎoshang", image: "NONE", english: "Good morning" },
      { word: "晚安", pinyin: "Wǎn'ān", image: "NONE", english: "Good night" },
      { word: "我爱你", pinyin: "Wǒ ài nǐ", image: "NONE", english: "I love you" },
      { word: "这是什么？", pinyin: "Zhè shì shénme?", image: "NONE", english: "What’s that?" },
      { word: "我想要更多", pinyin: "Wǒ xiǎng yào gèng duō", image: "NONE", english: "I want more" },
      { word: "我想要少一点", pinyin: "Wǒ xiǎng yào shǎo yīdiǎn", image: "NONE", english: "I want less" },
      { word: "你想要什么？", pinyin: "Nǐ xiǎng yào shénme?", image: "NONE", english: "What do you want?" },
      { word: "完成了", pinyin: "Wánchéngle", image: "NONE", english: "All done" },
      { word: "我需要", pinyin: "Wǒ xūyào", image: "NONE", english: "I need" },
      { word: "这只狗", pinyin: "Zhè zhī gǒu", image: "NONE", english: "This dog" },
      { word: "我们不知道狗是否友善", pinyin: "Wǒmen bù zhīdào gǒu shìfǒu yǒushàn", image: "NONE", english: "We don’t know if the dog is nice" },
      { word: "可以摸狗", pinyin: "Kěyǐ mō gǒu", image: "NONE", english: "You can pet the dog" },
      { word: "我可以做到", pinyin: "Wǒ kěyǐ zuòdào", image: "NONE", english: "I can do it" },
      { word: "可以吃", pinyin: "Kěyǐ chī", image: "NONE", english: "You can eat" },
      { word: "一点点", pinyin: "Yīdiǎn diǎn", image: "NONE", english: "A little bit" },
      { word: "很多", pinyin: "Hěn duō", image: "NONE", english: "A lot" },
    ]
  },
  pronouns: {
    label: "Pronouns",
    pinyinLabel: "Dàicí",
    chinese: "代词",
    words: [
      { word: "我", pinyin: "Wǒ", image: "🙋‍♂️", english: "I, Me" },
      { word: "你", pinyin: "Nǐ", image: "🙋‍♀️", english: "You" },
      { word: "他,她,它", pinyin: "Tā", image: "👨", english: "He, Him, She, Her, It" },
      { word: "我们", pinyin: "Wǒmen", image: "👥", english: "We, Us" },
      { word: "你们", pinyin: "Nǐmen", image: "👥", english: "You (plural)" },
      { word: "他们", pinyin: "Tāmen", image: "👫", english: "They, Them" }
    ]
  },
};
