const cacheName = 'mandarin-1e59fe641cc881f41892c42f6e59f60f';
const appShellFiles = [
  './cards/card-style.css',
  './cards/cards-4000.png',
  './cards/cards-icon-4000.png',
  './cards/cards.png',
  './cards/index.html',
  './cards/pwa.js',
  './cards/script.js',
  './data.js',
  './img/April.png',
  './img/August.png',
  './img/December.png',
  './img/February.png',
  './img/January.png',
  './img/July.png',
  './img/June.png',
  './img/March.png',
  './img/May.png',
  './img/November.png',
  './img/October.png',
  './img/September.png',
  './img/above.png',
  './img/afraid.png',
  './img/airconditioning.png',
  './img/airport.png',
  './img/allday.png',
  './img/almondmilk.png',
  './img/animals.png',
  './img/annoy.png',
  './img/areyouhungry.png',
  './img/badsmell.png',
  './img/ballcourt.png',
  './img/bambooshoots.png',
  './img/bathe.png',
  './img/be.png',
  './img/beautiful.png',
  './img/bedroom.png',
  './img/bedtime.png',
  './img/behind.png',
  './img/below.png',
  './img/bench.png',
  './img/big.jpg',
  './img/bite.png',
  './img/blanket.png',
  './img/blowyournose.png',
  './img/bokchoy.jpg',
  './img/book.png',
  './img/bored.png',
  './img/bottledwater.png',
  './img/bowl.png',
  './img/bridge.png',
  './img/bring.png',
  './img/bringbackpack.png',
  './img/brushteeth.png',
  './img/businesstrip.png',
  './img/butt.png',
  './img/buy.png',
  './img/call.png',
  './img/careful.png',
  './img/celery.png',
  './img/chalk.png',
  './img/christmas.png',
  './img/cilantro.png',
  './img/cinema.png',
  './img/clean.png',
  './img/cleaning.png',
  './img/closethedoor.png',
  './img/cold.png',
  './img/color.png',
  './img/come.png',
  './img/comfortable.png',
  './img/creek.png',
  './img/cup.png',
  './img/cut.png',
  './img/dad.png',
  './img/daikon.jpg',
  './img/daughter.png',
  './img/day.png',
  './img/dead.png',
  './img/diaper.png',
  './img/didyousleepwell.png',
  './img/diet.png',
  './img/difficult.png',
  './img/dirty.png',
  './img/dirtylaundry.png',
  './img/do.png',
  './img/donttouch.png',
  './img/drain.png',
  './img/drink.png',
  './img/drive.png',
  './img/dropped.png',
  './img/dry.png',
  './img/dumb.png',
  './img/earprotection.png',
  './img/easy.png',
  './img/eat.png',
  './img/eatbreakfast.png',
  './img/eatdinner.png',
  './img/eatlunch.png',
  './img/escalator.png',
  './img/everyone.png',
  './img/excited.png',
  './img/exercise.png',
  './img/far.png',
  './img/fart.png',
  './img/few.png',
  './img/fifthfloor.png',
  './img/fingers.png',
  './img/finishwork.png',
  './img/floor.png',
  './img/floss.png',
  './img/follow.png',
  './img/fork.png',
  './img/freezer.png',
  './img/fridge.png',
  './img/fruit.png',
  './img/fun.png',
  './img/garage.png',
  './img/givebook.png',
  './img/glass.png',
  './img/go.png',
  './img/goodsmell.png',
  './img/gotowork.png',
  './img/grab.png',
  './img/grabbook.png',
  './img/grass.png',
  './img/greenbean.jpg',
  './img/greenonion.jpg',
  './img/ground.png',
  './img/hair.png',
  './img/hard.png',
  './img/have.png',
  './img/healthy.png',
  './img/heisdrawing.png',
  './img/help.png',
  './img/hit.png',
  './img/homeoffice.png',
  './img/hope.png',
  './img/hot.png',
  './img/hotfood.png',
  './img/hour.png',
  './img/howmuch.png',
  './img/howoldareyou.png',
  './img/hungry.png',
  './img/idontunderstand.png',
  './img/iforgot.png',
  './img/iloveyou.png',
  './img/imhappy.png',
  './img/iminpain.png',
  './img/in.png',
  './img/infront.png',
  './img/iwantmore.png',
  './img/joke.png',
  './img/jump.png',
  './img/kitchen.png',
  './img/knife.png',
  './img/knowperson.png',
  './img/language.png',
  './img/lastweek.png',
  './img/lastyear.png',
  './img/late.png',
  './img/laundry.png',
  './img/learn.png',
  './img/library.png',
  './img/lick.png',
  './img/liedown.png',
  './img/like.png',
  './img/listen.png',
  './img/live.png',
  './img/livingroom.png',
  './img/lonely.png',
  './img/look.png',
  './img/looksdelicious.png',
  './img/low.png',
  './img/mall.png',
  './img/many.png',
  './img/mean.png',
  './img/meeting.png',
  './img/menu.png',
  './img/minute.png',
  './img/missyou.png',
  './img/mom.png',
  './img/month.png',
  './img/more.png',
  './img/movie.png',
  './img/mulch.jpg',
  './img/name.png',
  './img/napkin.png',
  './img/naptime.png',
  './img/near.png',
  './img/neighbor.png',
  './img/new.png',
  './img/nextto.png',
  './img/nextweek.png',
  './img/nextyear.png',
  './img/nice.png',
  './img/noodles.png',
  './img/now.png',
  './img/open.png',
  './img/openthewindow.png',
  './img/out.png',
  './img/outside.png',
  './img/oven.png',
  './img/pajamas.png',
  './img/pan.png',
  './img/park.png',
  './img/pathway.png',
  './img/peanutbutter.png',
  './img/peas.png',
  './img/pee.png',
  './img/pickle.png',
  './img/pillow.png',
  './img/pink.png',
  './img/plate.png',
  './img/play.png',
  './img/playequipment.png',
  './img/playground.png',
  './img/please.png',
  './img/poke.png',
  './img/popsicle.png',
  './img/pot.png',
  './img/pull.png',
  './img/putcupontable.png',
  './img/puton.png',
  './img/question.png',
  './img/read.png',
  './img/rectangle.png',
  './img/relaxed.png',
  './img/restaurant.png',
  './img/river.png',
  './img/salty.png',
  './img/sandbox.png',
  './img/school.png',
  './img/seaweed.png',
  './img/seconddog.png',
  './img/shampoo.png',
  './img/shy.png',
  './img/sing.png',
  './img/sit.png',
  './img/sixthirty.png',
  './img/slippers.png',
  './img/small.jpg',
  './img/smart.png',
  './img/smellybook.png',
  './img/snack.png',
  './img/sneakily.png',
  './img/snot.png',
  './img/soft.png',
  './img/son.png',
  './img/soysauce.png',
  './img/spicy.png',
  './img/stairs.png',
  './img/standup.png',
  './img/steal.png',
  './img/stick.png',
  './img/stickers.png',
  './img/sticky.png',
  './img/store.png',
  './img/stove.png',
  './img/sugar.png',
  './img/supermarket.png',
  './img/sweet.png',
  './img/swimmingpool.png',
  './img/swing.png',
  './img/swish.png',
  './img/table.png',
  './img/takeoff.png',
  './img/takepicture.png',
  './img/tall.png',
  './img/teach.png',
  './img/tell.png',
  './img/thing.png',
  './img/thirsty.png',
  './img/thisdog.png',
  './img/threeoclock.png',
  './img/throw.png',
  './img/throwaway.png',
  './img/tickles.png',
  './img/tissue.png',
  './img/today.png',
  './img/toes.png',
  './img/tomorrow.png',
  './img/towel.png',
  './img/toy.png',
  './img/tunnel.png',
  './img/turnleft.png',
  './img/turnoffthelight.png',
  './img/turnonthelight.png',
  './img/tvshow.png',
  './img/understand.png',
  './img/use.png',
  './img/vacuum.png',
  './img/vinegar.png',
  './img/wakeup.png',
  './img/wall.png',
  './img/washhands.png',
  './img/water.png',
  './img/weather.png',
  './img/week.png',
  './img/wet.png',
  './img/whatareyouwatching.png',
  './img/whatdoyouwant.png',
  './img/whatisthat.png',
  './img/whattimeisit.png',
  './img/when.png',
  './img/whendoweleave.png',
  './img/which.png',
  './img/white.png',
  './img/who.png',
  './img/wipe.png',
  './img/word.png',
  './img/workathome.png',
  './img/worried.png',
  './img/year.png',
  './img/yesterday.png',
  './index.html',
  './mcb-1154.png',
  './mcb-icon-1024.png',
  './mcb-icon-4000.png',
  './mcb.png',
  './pwa.js',
  './script.js',
  './style.css',
];

async function updateCache(request, response) {
  if (response && response.ok) {
    const cache = await caches.open(cacheName);
    await cache.put(request, response.clone());
  }
}

function shouldUseNetworkFirst(request) {
  const url = new URL(request.url);
  return request.mode === 'navigate' || url.pathname.endsWith('.html') || url.pathname.endsWith('.js') || url.pathname.endsWith('.css');
}

self.addEventListener('install', (e) => {
  e.waitUntil((async () => {
    const cache = await caches.open(cacheName);
    await cache.addAll(appShellFiles);
  })());
});

self.addEventListener('activate', (e) => {
  e.waitUntil((async () => {
    const keys = await caches.keys();
    for (const key of keys) {
      if (key !== cacheName) {
        await caches.delete(key);
      }
    }
  })());
});

self.addEventListener('fetch', (e) => {
  if (e.request.method !== 'GET') {
    return;
  }

  e.respondWith((async () => {
    const cached = await caches.match(e.request);
    if (!cached) {
      return fetch(e.request);
    }

    if (!shouldUseNetworkFirst(e.request)) {
      return cached;
    }

    try {
      const response = await fetch(e.request);
      await updateCache(e.request, response);
      return response;
    } catch (error) {
      return cached;
    }
  })());
});
