const PCEImageLibrary = {
  pceImageForName: function(name) {
    let keyName = name.toLowerCase().replace(/[\s\-]+/g, '')
    if (!Object.keys(this).includes(keyName)) {
      keyName = "hi"
    }
    const imageStr = this[keyName].imageStr
    return new PCEImage(imageStr)
  },


  WaterStand0: {
imageStr: `.:#00000000
_:#425561
W:#FFFFFF
@:#A7AFB4
A:#000000
B:#425561
M:#002D49
T:#AF0003

.......................................
.......................................
....A...........A......................
...AWA.........AWA.....................
...AWA.........AWA.....................
...AWWA.......AWWA.....................
....AWWAAAAAAAWWA......................
....AAA@@@@@@@AA.......................
....A@@@@@@@@@@@A......................
....A@AA@@@@@AA@@A.....................
...A@AWAA@@@AWAA@A.....................
...A@ABAA@@@ABAA@@A....................
...A@AAAA@@@AAAA@@A....................
...A@@@@@@@@@@@@@@A.........AAA........
..A@@@@M@@M@@@@@@@A.........A@@AA......
..A@@@@@@@@@@@@@@@A..........A@@@A.....
..A@@@MMMMMMM@@@@@A...........A@@@A....
..A@@MMTTTTTMM@@@A............A@@@A....
...A@@MMTTTMM@@@@A.............A@@@A...
....A@@@MMM@@@@@A..............A@@@A...
.....A@@@@@@@@@@A..............A@@@@A..
......A@@@@@@@@A...............A@@@@A..
......A@@@@@@@@A...............A@@@@A..
.....A@@@@@@@@@A..............A@@@@@A..
.....A_@_@_@_@@A..............A@@@@@A..
.....A_______@@A.............A@@@@@@A..
....A_________@A............A@@@@@@@A..
....A_________@@A.........AA@@@@@@@@A..
....A_________@@@AA.....AA@@@@@@@@@A...
....A_________@@@@@AAAAA@@@@@@@@@@@A...
....A__________@@@@@@@@@@@@@@@@@@@@A...
....AB_________@@@@@@@@@@@@@@@@@@@A....
.....AB________B@@@@@@@@@@@@@@@@@@A....
.....AB________B@@@@@@@@@@@@@@@@@A.....
......AB_______BBB@@@@@@@@@@@@@@A......
......AB________BBBB@@@@@@@@@@@A.......
.......ABB_____BBBBBBB@@@@@@BBA........
........ABBBBBBBBBBBBBBBBBBBAA.........
.........AABBBBBBBBBBBBBBAAA...........
...........AAAABBBBBBAAAA..............
...............AAAAAA..................
.......................................
.......................................`
  },
  
  
  WaterStand1: {
imageStr:`.:#00000000
_:#425561
W:#FFFFFF
@:#A7AFB4
A:#000000
B:#425561
M:#002D49
T:#AF0003

.......................................
.......................................
......A...........A....................
.....AWA.........AWA...................
.....AWA.........AWA...................
.....AWWA.......AWWA...................
......AWWAAAAAAAWWA....................
......AAA@@@@@@@AA.....................
......A@@@@@@@@@@@A....................
......A@AA@@@@@AA@@A...................
.....A@AWAA@@@AWAA@A...................
.....A@ABAA@@@ABAA@@A..................
.....A@AAAA@@@AAAA@@A..................
.....A@@@@@@@@@@@@@@A......AAA.........
....A@@@@M@@M@@@@@@@A......A@@AA.......
....A@@@@@@@@@@@@@@@A.......A@@@A......
....A@@@MMMMMMM@@@@@A........A@@@A.....
....A@@@MMMMMMM@@@@A.........A@@@A.....
.....A@@@@@@@@@@@@@A..........A@@@A....
......A@@@@@@@@@@@A...........A@@@A....
.......A@@@@@@@@@A............A@@@@A...
......A@@@@@@@@@A.............A@@@@A...
......A@@@@@@@@A..............A@@@@A...
.....A@@@@@@@@@A.............A@@@@@A...
.....A_@_@_@_@@A.............A@@@@@A...
.....A_______@@A.............A@@@@@A...
.....A________@A............A@@@@@@A...
.....A________@@A.........AA@@@@@@@A...
.....A________@@@AA.....AA@@@@@@@@@A...
.....A________@@@@@AAAAA@@@@@@@@@@@A...
.....A_________@@@@@@@@@@@@@@@@@@@@A...
.....A_________@@@@@@@@@@@@@@@@@@@A....
.....AB________B@@@@@@@@@@@@@@@@@@A....
......A________B@@@@@@@@@@@@@@@@@A.....
......AB_______BBB@@@@@@@@@@@@@@A......
......AB________BBBB@@@@@@@@@@@A.......
.......ABB_____BBBBBBB@@@@@@BBA........
........ABBBBBBBBBBBBBBBBBBBAA.........
.........AABBBBBBBBBBBBBBAAA...........
...........AAAABBBBBBAAAA..............
...............AAAAAA..................
.......................................
.......................................`
  },
  
  
  FireStand0: {
imageStr:`.:#00000000
_:#FFFFFF
@:#FF6C24
A:#000000
B:#8A0000
E:#B40000
F:#FF5B03
Y:#FFFB03

..................................
..................................
...........B.B....................
..........BFBFB...................
.........BFYFYFB..................
.........BFYFYFB..................
........BFYFYFYFB.................
........BFYFYFYFB.................
........BAAAAAFB..................
.......AA@@@@@AA..................
......A@@@@@@@@@A.................
.....A@@@@@@@@@@@A................
....A@@@@@@@@@@@@@A...............
....AAA@@@AAA@@@@@A...............
...A@@@@@@@@@@@@@@@A..............
...AAAA@@@AAA@@@@@@A..............
...AA_EA@@A_EA@@@@@A..............
...AAEEA@@AEEA@@@@@AA.............
....AAAA@@@AAA@@@@@A_AAA..........
...A@@@@@@@@@@@@@@A__ABBAA........
...A@AAAAAAAA@@@@@AA__AAAAA.......
....A@@@@@@@@@@@@AA@A_ABBBBA......
.....A@@@@@@@@@@AA@@A__ABBBBA.....
......AA@@@@AAAAA@@@@A_ABBBBA.....
........AAAAABBBA@@@@A_ABBBBBA....
........AABBBBBA@@@@@A_ABBBBBA....
......AA@ABBBBBA@@@@@A_ABBBBBBA...
....AA@@@AAABBA@@@@@@A__ABBBBAA...
...A_@@@@@ABAAA@@_@@ABA_ABBAABA...
....A@_@@@ABBBA_A@@@ABA__AABBBA...
...A_@@@@AAABBBABA_ABBBA__ABBBA...
....AAAAA...ABBABBAABBBAA__ABBA...
............AAABAABBABA@@A__BAA...
...........A@@ABBABBBA@@@@A_AA....
...........A@@@ABBABBA@@@@@AA.....
...........A@@@@AABABA@@@@@A......
............A@@@@@AAAA@@@@@A......
............AA@@@@AABA@@@@@A......
...........A_@_@@A..AAA@@@AA......
............AAAAA.....A_@@A.......
.......................AAA........
..................................
..................................`
  },
  
  FireStand1: {
imageStr:`.:#00000000
_:#FFFFFF
@:#FF6C24
A:#000000
B:#8A0000
E:#B40000
F:#FF5B03
Y:#FFFB03

..................................
..................................
.............B.B..................
............BFBFB.................
...........BFYFYFB................
...........BFYFYFB................
..........BFYFYFYFB...............
.........BFYFYFYFB................
.........BAAAAAFB.................
.......AA@@@@@AA..................
......A@@@@@@@@@A.................
.....A@@@@@@@@@@@A................
....A@@@@@@@@@@@@@A...............
....AAA@@@AAA@@@@@A...............
...A@@@@@@@@@@@@@@@A..............
...AAAA@@@AAA@@@@@@A..............
...AA_EA@@A_EA@@@@@A..............
...AAAAA@@AAAA@@@@@AA.............
....A@@@@@@@@@@@@@@A_AAA..........
...A@@@@@@@@@@@@@@A__ABBAA........
...A@AAAAAAAA@@@@@AA__AAAAA.......
....A@@@@@@@@@@@@AA@A_ABBBBA......
.....A@@@@@@@@@@AA@@A__ABBBBA.....
......AA@@@@AAAAA@@@@A_ABBBBA.....
........AAAAABBA@@@@@A_ABBBBBA....
.........AABBBBA@@@@@A_ABBBBBA....
........A@ABBBBA@@@@@A_ABBBBBBA...
.......A@@AAABA@@@@@@A__ABBBBAA...
......A@@@AABAA@@_@@ABA_ABBAABA...
.....A_@@@@ABBA_A@@@ABA__AABBBA...
.....A@@_@@AABBABA_ABBBA__ABBBA...
.....A_@@@A..ABBABBAABBBAA__ABA...
......AAAA...AAABAABABA@@@A__AA...
.............A@ABBABBA@@@@A_AA....
.............A@@ABBABA@@@@@AA.....
.............A@@@AABBA@@@@@A......
..............A@@@@AAA@@@@@A......
..............AA@@@ABA@@@@@A......
.............A_@_@A.AAA@@@AA......
.............AAAAA....A_@_A.......
.......................AAA........
..................................
..................................`
  },
  
  
  GrassStand0: {
imageStr:`.:#00000000
_:#FFFFFF
@:#004C28
A:#000000
B:#009B52
T:#42D000
P:#FF8CCF

...........................................
...........................................
...........AAAAAA...............P..P.......
.........AABBBBBBAA............APPPPA......
........ABBBBBBBBB@A..........ABBPPPBA.....
........ABBBBBBBBBB@A.........ABBPPPBA.....
.......ABBBBBBBBBBBBA.........ABBBPBBBA....
......AP@BBBBBB@PBBBBA.......ABBB@P@BBA....
......APPBBBBBBPPABBBA.......ABB@B@B@BBA...
......AA@BBBBBBAAABBBA.......AB@BB@BB@BA...
......A@BBBBBBBAAABBB@A.....ABB@BB@BB@BBA..
......ABBBBBBBB@A@BBBBA.....ABB@BB@BB@BBA..
.....ABBBBBBBBBBBBBBBBA.....ABB@BB@BB@BBA..
....AABBBBBBBBBBBBBBBBA.....ABB@BB@BB@BBA..
...A_ABBBBBBBBBB@AABBBA......AB@BB@BB@BBA..
...A@BABBB@BBBB@A@BBBB@A.....ABB@B@BB@BBA..
...ABBBABBBBBAAAABBBBBBA......ABB@@@@BBA...
....ABBBAAAAA@@ABB@BBBB@A......ABB@@BBBA...
.....ABBB@A@@AAB@@BBBBBB@A......AABBB@A....
......A@BB@AABB@@ABBBB@BBA........ABBA.....
.......AAB@@@A@@ABBBBBABBBA.......AB@A.....
........AAA@@@@BABBBBBABBBBA......AB@A.....
...........AABBABBBBB@@BBBBA.....ABB@A.....
............ATTABBBBBATBBBBBA....ABB@A.....
............ATABBBBB@ATBBBBBA..AABBB@A.....
............ATA@BBB@ATTBBBBB@AABBBB@@A.....
...........AATA_@@@ATTBBBBBBBABBBBB@A......
..........ABBA_AA_ATT@BBBBBBBABBBB@@A......
.........ABBBATTTATT@BBBBBBBBABB@@@A.......
.........ABBBBATTTTTABBBBBBBBA@@@@A........
.........ABBBBBATTTT@BBBBBBBBA@@@A.........
.........ABBBBB@@BTTT@BBBBBB@@@AA..........
..........ABBBB@@AABBABBBBBB@AA............
..........AABB@@@A.AAAA@BBBAA..............
.........ABB@A@@A.....AA@@@BA..............
........ABBABB@A.....ABBBBBBA..............
.........AAAAAA......AA@BABA...............
......................AAAAA................
...........................................
...........................................`
  },

  GrassStand1: {
imageStr:`.:#00000000
_:#FFFFFF
@:#004C28
A:#000000
B:#009B52
T:#42D000
P:#FF8CCF

...........................................
...........................................
...........AAAAAA..................P..P....
.........AABBBBBBAA...............APPPPA...
........ABBBBBBBBB@A.............ABPPPBA...
........ABBBBBBBBBB@A...........ABBPPPBA...
.......ABBBBBBBBBBBBA...........ABBBPBBBA..
......AP@BBBBBB@PBBBBA.........ABB@@P@BBA..
......APPBBBBBBPPABBBA........ABB@B@B@BBA..
......AA@BBBBBBAAABBBA........AB@BB@BB@BA..
......A@BBBBBBBAAABBB@A......ABB@BB@BB@BBA.
......ABBBBBBBBBBBBBBBA......ABB@BB@BB@BBA.
.....ABBBBBBBBBBBBBBBBA......ABB@BB@BB@BBA.
.....ABBBBBBBBBBBBBBBBA......ABB@BB@BB@BBA.
....AABBBBBBBBBBBBBBBBA.......AB@BB@BB@BBA.
...A_AABBBB@BBBBA@BBBB@A......ABB@B@BB@BBA.
...A@BBABBBBBBBAABBBBBBA.......ABB@@@@BBA..
...ABBBAAAAAAAAABB@BBBB@A.......ABB@@BBBA..
....ABBBB@AAAABB@@BBBBBB@A.......AABBB@A...
.....ABBB@BBBBB@@ABBBB@BBA.........ABBA....
......A@BB@@@A@@ABBBBBABBBA........AB@A....
.......AABBBBBBABBBBBABBBBA.......AB@A.....
........AAAAABABBBBB@@BBBBA......ABB@A.....
............ATABBBBBATBBBBBA....ABB@A......
............AABBBBB@ATBBBBBA..AABBB@A......
............AA@BBB@ATTBBBBB@AABBBB@@A......
...........AAA_@@@ATTBBBBBBBABBBBB@A.......
...........AA_AA_ATT@BBBBBBBABBBB@@A.......
..........ABBATTTTT@BBBBBBBBABB@@@A........
..........ABBBATTTTABBBBBBBBA@@@@A.........
..........ABBBBATTT@BBBBBBBBA@@@A..........
..........ABBBB@@BTT@BBBBBB@@@AA...........
...........ABBB@@AABABBBBBB@AA.............
...........AAB@@@A.AAA@BBBAA...............
..........ABB@A@@A...AA@@@BA...............
.........ABBABB@A...ABBBBBBA...............
..........AAAAAA....AA@BABA................
.....................AAAAA.................
...........................................
...........................................`
  },
  
  
  Egg0: {
imageStr:`.:#00000000
_:#FFFFFF
A:#000000
B:#009B52

...............
......AAA......
.....A___A.....
....A___BBA....
...A____BBBA...
...AB____BBA...
..ABBB______A..
..ABBB_____BA..
..ABB__BB__BA..
..A___BBB__BA..
..A___BBB___A..
...AB_____BA...
....A____BA....
.....AAAAA.....
...............`
  },
  
  
  Egg1: {
imageStr:`.:#00000000
_:#FFFFFF
A:#000000
B:#009B52

...............
...............
......AAA......
.....A___A.....
....A___BBA....
...A____BBBA...
...AB____BBA...
..ABBB______A..
..ABBB_BB__BA..
..AB__BBB__BA..
..A___BBB__BA..
...AB_____BA...
....A____BA....
.....AAAAA.....
...............`
  },
  
  Egg2: {
imageStr:`.:#00000000
_:#FFFFFF
A:#000000
B:#009B52

...............
...............
...............
...............
.....AAAAA.....
....A___BBA....
...A____BBBA...
...AB____BBA...
..ABBB______A..
..ABBB_BB__BA..
..AB__BBB_BBA..
...AB_BBB_BA...
....A____BA....
.....AAAAA.....
...............`
  },


  ResearchCenter0: {
imageStr:`.:#00000000
_:#FFFFFF
C:#E5E5E5
A:#000000
D:#535353
G:#A1A1A1

................
..CCC.CCCC......
.CCC...CC.......
................
.AA..AA.........
.AGA.AGA........
.AGGAAGGA.......
.A_GGA_GGAAAAA..
.AG_GDG_GDGGGGA.
.AGG_DGG_DGDDGA.
.A_GGD_GGDGDDGA.
.AG_GDG_GDGDDGA.
.AGG_DGG_DGDDGA.
.AGGG_GGG_DGGGA.
.AGGGGGGGGDGGGA.
.AG_G_G_G_DG_GA.
.AG_G_G_G_DG_GA.
.AGGGGGGGGDAAAA.
.AAAAAAAAAA.....
................`
  },
  
  ResearchCenter1: {
imageStr:`.:#00000000
_:#FFFFFF
C:#E5E5E5
A:#000000
D:#535353
G:#A1A1A1

................
.CCC...CCC......
.CCCC.CCC.......
................
.AA..AA.........
.AGA.AGA........
.AGGAAGGA.......
.A_GGA_GGAAAAA..
.AG_GDG_GDGGGGA.
.AGG_DGG_DGDDGA.
.A_GGD_GGDGDDGA.
.AG_GDG_GDGDDGA.
.AGG_DGG_DGDDGA.
.AGGG_GGG_DGGGA.
.AGGGGGGGGDGGGA.
.AG_G_G_G_DG_GA.
.AG_G_G_G_DG_GA.
.AGGGGGGGGDAAAA.
.AAAAAAAAAA.....
................`
  },
  
  Tree: {
imageStr:`.:#00000000
O:#147A0E
L:#079600
I:#09BD00
T:#684505
B:#8F671C

.................
.....OOOOOOO.....
...OOIIIIIIIOO...
..OIIILLLLLIIIO..
..OILLLLLLLLLIO..
.OILLLLLLLLLLLIO.
.OLLLLLLLLLLLLLO.
.OLLLLLLLLLLLLLO.
.OLLLLLLLLLLLLLO.
..OOLLLLLLLLLOO..
....OOOOOOOOO....
......TBBBT......
......TBBBT......
......TBBBT......
......TBBBT......
......TBBBT......
......TBBBT......
.....TBBBBBT.....
....TTTTTTTTT....
.................`
  },
  
  Ore: {
imageStr:`.:#00000000
O:#303030
H:#AEB1C0
B:#5A5D6C

...................
.....OOOOOOOOO.....
....OBBBBBBBBBO....
...OBBHHHBHHHBBO...
..OBBHHHHBHHHHBBO..
.OBBHHHHHBHHHHHBBO.
.OBHHHHHBBBHHHHHBO.
.OBHHHHBBHBBHHHHBO.
.OBHHHBBHHHBBHHHBO.
.OBBBBBHHHHHBBBBBO.
.OBHHHBBHHHBBHHHBO.
.OBHHHHBBHBBHHHHBO.
.OBHHHHHBBBHHHHHBO.
.OBBHHHHHBHHHHHBBO.
..OBBHHHHBHHHHBBO..
...OBBHHHBHHHBBO...
....OBBBBBBBBBO....
.....OOOOOOOOO.....
...................`
  },

}
Object.freeze(PCEImageLibrary)
