const Tuning = {
    // FARMING
    FARM_GROWTH_INTERVAL_MS: 30000, // 30 seconds
    FARM_TREE_PROBABILITY: 0.4,     // 40%
    FARM_CARROT_PROBABILITY: 0.4,   // 40%
    FARM_SEED_PROBABILITY: 0.2,     // 20%

    // TREE GROWTH
    TREE_GROWTH_INTERVAL_MS: 60000, // 60 seconds
    TREE_GROWTH_PROBABILITY: 0.05,  // 5%

    // CHARACTERS
    CHARACTER_EXPLORE_INTERVAL_MS: 3000, // 3 seconds
    CHARACTER_MAX_MOVES: 10,
    CHARACTER_MAX_REPRODUCTIONS: 2,
    CHARACTER_REPRODUCTION_INTERVAL_MS: 5000, // 5 seconds
    CHARACTER_HATCH_CHECK_INTERVAL_MS: 5000, // 5 seconds
    EGG_MIN_HATCH_MS: 30000,   // 30 seconds
    EGG_MAX_HATCH_MS: 120000, // 120 seconds

    // BUILDINGS
    HOUSE_WOOD_COST: 20,
    RESEARCH_CENTER_WOOD_COST: 30,
    RESEARCH_CENTER_FOOD_COST: 20, // Carrots

    RESEARCH_AUTOHARVEST_WOOD_COST: 20,
    RESEARCH_AUTOHARVEST_FOOD_COST: 20,
    RESEARCH_AUTOFEED_WOOD_COST: 40,
    RESEARCH_AUTOFEED_FOOD_COST: 40,
    RESEARCH_MINING_WOOD_COST: 60,
    RESEARCH_MINING_FOOD_COST: 60,

    COMMUNICATION_TOWER_ORE_COST: 10,

    ORE_SPAWN_PROBABILITY_REVEAL: 0.3,   // 30% on reveal
    ORE_SPAWN_PROBABILITY_PERIODIC: 0.05, // 5% every 60s

    AUTO_AUTOMATION_INTERVAL_MS: 500, // 0.5 seconds
    AUTO_SAVE_INTERVAL_MS: 5000,      // 5 seconds

    // CAMERA
    CAMERA_LERP_FACTOR: 0.15,
    CAMERA_ZOOM_LERP_FACTOR: 0.3,
    CAMERA_EDGE_PAN_THRESHOLD: 100,
    CAMERA_MIN_CELL_SIZE: 1.25,

    // RENDERER
    //RENDERER_FEATURE_FLAG: "classic_2d",
    RENDERER_FEATURE_FLAG: "three_surface",
    THREE_SURFACE_CURVE_START_CELL_SIZE: 60,
    THREE_SURFACE_CURVE_END_CELL_SIZE: 18,
    THREE_SURFACE_RADIUS_SCALE_START: 4,
    THREE_SURFACE_TRANSITION_ENTER_CELL_SIZE: 18,
    THREE_SURFACE_TRANSITION_EXIT_CELL_SIZE: 22,
    THREE_SURFACE_GLOBE_ENTER_CELL_SIZE: 7,
    THREE_SURFACE_GLOBE_EXIT_CELL_SIZE: 9,
    THREE_SURFACE_SNAPSHOT_MAX_SIZE: 2048,
    THREE_SURFACE_GLOBE_LONGITUDE_TILES: 4,
    THREE_SURFACE_GLOBE_POLAR_FADE: 0.12,
    THREE_SURFACE_GLOBE_POLAR_COLOR: "#2A4363",

    // GLOBE
    GLOBE_TRANSITION_START_CELL_SIZE: 16,
    GLOBE_TRANSITION_END_CELL_SIZE: 4,
    GLOBE_ROTATION_SENSITIVITY: 0.005,
    GLOBE_LERP_FACTOR: 0.18,
    GLOBE_TRANSITION_RADIUS_SCALE: 3,
    GLOBE_CAMERA_SURFACE_DISTANCE: 3.25,
    GLOBE_CAMERA_FAR_DISTANCE: 120,
    GLOBE_CAMERA_SURFACE_FOV: 18,
    GLOBE_CAMERA_FAR_FOV: 34,

    // GENERATION
    GRID_SIZE: 300,
    SMOOTHING_ITERATIONS: 8,
    SMOOTHING_RADIUS: 2,
    INITIAL_ITEM_PROBABILITY: 0.06 // 6% chance
};

if (typeof module !== 'undefined' && module.exports) {
    module.exports = { Tuning };
}
